"""The play page's JavaScript, as one module.

Kept out of `site.py` because it is long and because it is real code rather than
a template: it imports `web/engine/` (copied to `outputs/site/engine/` on
export) and drives it against the map.

**The escaping rule that has bitten this repo twice.** This is a plain Python
triple-quoted string, so any backslash escape meant to reach the browser has to
be doubled here: a `\\n` written as `\\n` becomes a real newline before the file
is ever written, which is how a regex and a `join` were silently broken in two
earlier phases. `tests/test_js_syntax.py` runs `node --check` over the result,
which is what catches it now.
"""

PLAY_JS = """// The live game, played in this browser.
//
// Generated by hoc/export/play_js.py. The engine underneath is web/engine/,
// copied to engine/ on export — the same code the repository plays the game
// with, so a season computed here is the season the repository would have
// computed (docs/DETERMINISM.md).
//
// Nothing here is saved to the repository. Play is local, autosaved to
// IndexedDB so a closed tab does not lose it, and the banner says how many
// seasons are unsaved. Persistence is Phase 10-3.

import { loadRules } from './engine/rules.js';
import { loadReferenceMap } from './engine/adjacency.js';
import { WorldState } from './engine/state.js';
import { World, RULES_VERSION } from './engine/sim.js';

const RULES_FILES = __RULES_FILES__;
const REFERENCE_FILES = __REFERENCE_FILES__;
const UNCLAIMED_FILL = '__UNCLAIMED_FILL__';
const STOP_CONDITIONS = __STOP_CONDITIONS__;
const DB_NAME = 'house-of-cards-play';
const DB_STORE = 'worlds';

const el = (id) => document.getElementById(id);

// ------------------------------------------------------------------ assets --

// The engine reads files by their repository path; the site serves the rules
// under data/rules/ and the reference map under data/reference/. One place
// knows the difference.
function assetUrl(logical) {
  return logical.startsWith('rules/') ? `data/${logical}` : logical;
}

async function fetchAll(paths, onProgress) {
  const contents = new Map();
  let done = 0;
  for (const logical of paths) {
    const response = await fetch(assetUrl(logical));
    if (!response.ok) throw new Error(`could not load ${logical} (${response.status})`);
    contents.set(logical, await response.text());
    done += 1;
    onProgress(done, paths.length);
  }
  return contents;
}

// ------------------------------------------------------------- persistence --

function openDb() {
  return new Promise((resolve, reject) => {
    const request = indexedDB.open(DB_NAME, 1);
    request.onupgradeneeded = () => {
      const db = request.result;
      if (!db.objectStoreNames.contains(DB_STORE)) db.createObjectStore(DB_STORE);
    };
    request.onsuccess = () => resolve(request.result);
    request.onerror = () => reject(request.error);
  });
}

async function idbGet(key) {
  try {
    const db = await openDb();
    return await new Promise((resolve, reject) => {
      const request = db.transaction(DB_STORE, 'readonly').objectStore(DB_STORE).get(key);
      request.onsuccess = () => resolve(request.result ?? null);
      request.onerror = () => reject(request.error);
    });
  } catch (error) {
    // A private window, or storage switched off. The page still plays; it just
    // cannot remember, and saying so is better than failing to load.
    return null;
  }
}

async function idbPut(key, value) {
  try {
    const db = await openDb();
    await new Promise((resolve, reject) => {
      const store = db.transaction(DB_STORE, 'readwrite').objectStore(DB_STORE);
      const request = store.put(value, key);
      request.onsuccess = () => resolve();
      request.onerror = () => reject(request.error);
    });
    return true;
  } catch (error) {
    return false;
  }
}

async function idbDelete(key) {
  try {
    const db = await openDb();
    await new Promise((resolve) => {
      const store = db.transaction(DB_STORE, 'readwrite').objectStore(DB_STORE);
      const request = store.delete(key);
      request.onsuccess = () => resolve();
      request.onerror = () => resolve();
    });
  } catch (error) { /* nothing to clear */ }
}

// ------------------------------------------------------------------- state --

const app = {
  world: null,
  rules: null,
  map: null,
  committedSeason: 0,
  committedSha: null,
  // Every season this browser has played, so the scrubber can walk back through
  // them and Undo can throw the later ones away. One entry per season: the
  // record the engine returned, plus the fills the map showed.
  history: [],
  viewing: null,
  timer: null,
  speed: __DEFAULT_SPEED__,
  stopOn: new Set(),
  filter: '',
};

function currentSeason() {
  return app.world ? app.world.seasonNo : 0;
}

function unsavedCount() {
  return Math.max(0, currentSeason() - app.committedSeason);
}

// -------------------------------------------------------------- the map ----

// fed_id -> fill, from the live world. The index page's map uses each house's
// primary colour for every riding it holds (hoc/export/map.py house_fills with
// use_secondary false); this is that rule, against the in-memory state.
function fillsNow() {
  const fills = new Map();
  for (const holding of app.world.state.holdings) {
    if (holding.releasedEventId !== null) continue;
    const [primary] = app.world.houseColours(holding.house);
    fills.set(holding.fedId, primary || UNCLAIMED_FILL);
  }
  return fills;
}

let pathByFed = new Map();

function indexPaths() {
  pathByFed = new Map();
  for (const path of document.querySelectorAll('#map-fills path')) {
    pathByFed.set(path.getAttribute('data-fed'), path);
  }
}

// Recolour only what changed, and flash it. Repainting all 343 paths every
// season at twelve seasons a second is what would make this page stutter on a
// phone; in a normal season fewer than five ridings change hands.
function paintFills(fills, { flash = true } = {}) {
  const changed = [];
  for (const [fedId, path] of pathByFed) {
    const next = fills.get(fedId) || UNCLAIMED_FILL;
    if (path.getAttribute('fill') === next) continue;
    path.setAttribute('fill', next);
    changed.push(path);
  }
  if (!flash) return changed.length;
  for (const path of changed) {
    path.classList.remove('just-changed');
    // Reading offsetWidth restarts the animation when the same riding changes
    // hands twice in quick succession.
    void path.getBoundingClientRect();
    path.classList.add('just-changed');
  }
  window.setTimeout(() => {
    for (const path of changed) path.classList.remove('just-changed');
  }, 900);
  return changed.length;
}

// ----------------------------------------------------------- the chrome ----

function renderStatus() {
  const world = app.world;
  const active = world.state.activeHouses().length;
  const held = world.state.totalCurrentHoldings();
  const bands = world.eras
    .map((era) => {
      const value = world.currentClimate(era.id);
      const shown = value === null ? '—' : (value > 0 ? `+${value}` : String(value));
      return `<span class="stat"><b>${escapeHtml(era.name)}</b> ${shown}</span>`;
    })
    .join('');
  el('play-status').innerHTML =
    `<span class="stat"><b>Season</b> ${currentSeason()}</span>`
    + `<span class="stat"><b>Houses</b> ${active}</span>`
    + `<span class="stat"><b>Ridings</b> ${held} of 343</span>`
    + bands;
}

function renderLegend() {
  const world = app.world;
  const counts = new Map();
  for (const holding of world.state.holdings) {
    if (holding.releasedEventId === null) {
      counts.set(holding.house, (counts.get(holding.house) || 0) + 1);
    }
  }
  const rows = [...counts.entries()]
    .filter(([house]) => world.state.house(house)?.status === 'active')
    .sort((a, b) => b[1] - a[1] || (a[0] < b[0] ? -1 : 1))
    .map(([house, count]) => {
      const [primary] = world.houseColours(house);
      return `<li><button type="button" class="legend-house" data-house="${escapeHtml(house)}">`
        + `<span class="swatch" style="background:${escapeHtml(primary || UNCLAIMED_FILL)}"></span>`
        + `<span class="legend-name">${escapeHtml(house)}</span>`
        + `<span class="legend-count">${count}</span></button></li>`;
    });
  el('play-legend').innerHTML = rows.join('');
}

function renderHouseFilter() {
  const select = el('feed-filter');
  const chosen = select.value;
  const names = app.world.state.activeHouseNames();
  select.innerHTML = '<option value="">every house</option>'
    + names.map((h) => `<option>${escapeHtml(h)}</option>`).join('');
  select.value = names.includes(chosen) ? chosen : '';
}

function renderInterveneHouses() {
  const names = app.world.state.activeHouseNames();
  for (const id of ['iv-house', 'iv-other']) {
    const select = el(id);
    if (!select) continue;
    const chosen = select.value;
    select.innerHTML = names.map((h) => `<option>${escapeHtml(h)}</option>`).join('');
    if (names.includes(chosen)) select.value = chosen;
  }
}

function escapeHtml(value) {
  return String(value)
    .replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

// House names in a chronicle line become buttons that open the panel, the way
// the site's chronicle links them to house pages. Longest first, so "Fraser 2"
// is matched before "Fraser".
function linkHouses(line) {
  const names = app.world.state.activeHouseNames()
    .slice()
    .sort((a, b) => b.length - a.length);
  let html = escapeHtml(line);
  for (const name of names) {
    const safe = escapeHtml(name);
    if (!html.includes(safe)) continue;
    html = html.split(safe).join(
      `<button type="button" class="house-link" data-house="${safe}">${safe}</button>`,
    );
    break; // one link per line is enough, and avoids nesting one name inside another
  }
  return html;
}

function appendFeed(season, lines, { stopped = null } = {}) {
  const feed = el('feed');
  const item = document.createElement('li');
  item.className = 'feed-season';
  item.setAttribute('data-season', String(season));
  const body = lines.length
    ? lines.map((line) => `<p>${linkHouses(line)}</p>`).join('')
    : '<p class="meta">A quiet season.</p>';
  const halt = stopped && stopped.length
    ? `<p class="feed-stop">Stopped: ${escapeHtml(stopped.join(', '))}</p>`
    : '';
  item.innerHTML = `<h3>Season ${season}</h3>${body}${halt}`;
  feed.prepend(item);
  applyFilter();
  // A long game would otherwise grow the DOM without bound; the scrubber and
  // the history keep the record, the feed only shows the recent past.
  while (feed.children.length > 120) feed.removeChild(feed.lastChild);
}

function applyFilter() {
  const wanted = app.filter;
  for (const item of el('feed').children) {
    if (!wanted) {
      item.hidden = false;
      continue;
    }
    item.hidden = !item.textContent.includes(wanted);
  }
}

function renderUnsaved() {
  const count = unsavedCount();
  const banner = el('unsaved');
  banner.hidden = count === 0;
  if (count === 0) return;
  banner.textContent =
    `${count} unsaved season${count === 1 ? '' : 's'} — saving arrives in the next update.`;
}

function renderScrubber() {
  const slider = el('play-season');
  const lowest = app.committedSeason;
  const highest = currentSeason();
  slider.min = String(Math.max(1, lowest));
  slider.max = String(Math.max(1, highest));
  if (app.viewing === null || app.viewing > highest) app.viewing = highest;
  slider.value = String(app.viewing);
  el('play-season-label').textContent = `season ${app.viewing}`;
  el('play-undo').disabled = app.viewing >= highest || app.viewing < lowest;
}

// -------------------------------------------------------------- the panel --

function showHouse(house) {
  const world = app.world;
  const row = world.state.houseRow(house);
  if (row === undefined) return;
  const holder = world.holder(house);
  const holdings = world.state.holdingsOf(house);
  const objectives = world.state.heldObjectives(house);
  const [primary] = world.houseColours(house);
  const stat = (label, value) => `<tr><th scope="row">${label}</th><td>${value}</td></tr>`;
  el('panel-body').innerHTML =
    `<h3><span class="swatch" style="background:${escapeHtml(primary || UNCLAIMED_FILL)}"></span>`
    + `${escapeHtml(row.peerage || house)}</h3>`
    + `<p class="meta">${escapeHtml(row.community || '')} · ${escapeHtml(row.tag || '')}`
    + ` · personal year ${world.personalYear(house)}</p>`
    + (holder
      ? `<p>${escapeHtml(holder.name)}, aged ${holder.age}</p>`
      : '<p class="meta">No holder.</p>')
    + '<table class="stats">'
    + stat('Capital', row.capital) + stat('Influence', row.influence)
    + stat('Cohesion', row.cohesion) + stat('Ambition', row.ambition)
    + stat('Ridings', holdings.length)
    + stat('Enclosed', row.enclosed ? 'yes' : 'no')
    + '</table>'
    + (objectives.length
      ? `<p><b>Objectives</b><br>${objectives.map(escapeHtml).join('<br>')}</p>`
      : '<p class="meta">No objectives standing.</p>')
    + `<p class="meta">${holdings.map((h) => escapeHtml(world.ridingName(h.fedId))).join(', ')}</p>`;
  el('panel').hidden = false;
}

// ------------------------------------------------------------- playing -----

function renderAll({ flash = false } = {}) {
  paintFills(fillsNow(), { flash });
  renderStatus();
  renderLegend();
  renderHouseFilter();
  renderInterveneHouses();
  renderUnsaved();
  renderScrubber();
}

// Which of the armed stop conditions this season met. The engine works it out
// from its own event deltas (World.stopConditions, a mirror of hoc/sim.py's
// _stop_conditions), so the browser stops on exactly what a repository run
// would stop on.
function stopsHit(record) {
  const hit = app.world.stopConditions(record.season);
  return [...hit].filter((name) => app.stopOn.has(name)).sort();
}

function playOne() {
  const record = app.world.runSeason();
  const stopped = stopsHit(record);
  app.history.push({ season: record.season, record });
  app.viewing = record.season;
  appendFeed(record.season, record.chronicle, { stopped });
  renderAll({ flash: true });
  save();
  return stopped;
}

let runRemaining = 0;

function tick() {
  if (app.viewing !== currentSeason()) {
    // The director has scrubbed back; playing on from here would branch the
    // game silently, so stop instead and let them Undo or return to the head.
    pause();
    return;
  }
  const stopped = playOne();
  if (stopped.length) {
    pause();
    return;
  }
  if (runRemaining > 0) {
    runRemaining -= 1;
    if (runRemaining === 0) pause();
  }
}

function play() {
  if (app.timer !== null) return;
  el('play-toggle').textContent = 'Pause';
  el('play-toggle').classList.add('playing');
  app.timer = window.setInterval(tick, Math.round(1000 / app.speed));
}

function pause() {
  if (app.timer !== null) window.clearInterval(app.timer);
  app.timer = null;
  runRemaining = 0;
  el('play-toggle').textContent = 'Play';
  el('play-toggle').classList.remove('playing');
}

// ------------------------------------------------------------- saving ------

function snapshotKey() {
  return `world:${app.committedSha || 'unknown'}`;
}

async function save() {
  const payload = {
    savedAt: new Date().toISOString(),
    committedSeason: app.committedSeason,
    committedSha: app.committedSha,
    season: currentSeason(),
    snapshot: app.world.state.toSnapshot(app.world),
  };
  await idbPut(snapshotKey(), payload);
}

// ------------------------------------------------------------- start up ----

async function boot() {
  const progress = el('load-progress');
  const say = (text) => { progress.textContent = text; };

  say('Loading the rules and the map…');
  const logical = RULES_FILES.map((n) => `rules/${n}`)
    .concat(REFERENCE_FILES.map((n) => `data/reference/${n}`));
  const contents = await fetchAll(logical, (done, total) => {
    say(`Loading the rules and the map… ${done} of ${total}`);
  });
  const read = (path) => {
    const text = contents.get(path);
    if (text === undefined) throw new Error(`${path} was not fetched`);
    return text;
  };

  say('Reading the world…');
  const worldResponse = await fetch('data/world.json');
  if (!worldResponse.ok) throw new Error(`could not load the world (${worldResponse.status})`);
  const committed = await worldResponse.json();

  app.rules = loadRules(read);
  app.map = loadReferenceMap(read);
  app.committedSeason = committed.season || 0;
  app.committedSha = committed.last_season_sha256;

  if (committed.rules_version !== RULES_VERSION) {
    throw new Error(
      `this world was played under rules ${committed.rules_version} and the engine here is`
      + ` ${RULES_VERSION}`,
    );
  }

  // A local game left in this browser, if it is ahead of the committed world
  // and was resumed from the same commit.
  let snapshot = committed;
  const stored = await idbGet(snapshotKey());
  if (stored && stored.season > app.committedSeason
      && stored.committedSha === app.committedSha) {
    const resume = window.confirm(
      `This browser has a local game ${stored.season - app.committedSeason} season(s)`
      + ` ahead of the published one (season ${stored.season}).`
      + '\\n\\nOK to resume it, or Cancel to discard it and start from the published world.',
    );
    if (resume) snapshot = stored.snapshot;
    else await idbDelete(snapshotKey());
  }

  app.world = new World({
    state: WorldState.load(snapshot, app.map),
    rules: app.rules,
    worldSeed: snapshot.world_seed,
  });
  app.viewing = currentSeason();

  indexPaths();
  wire();
  renderAll({ flash: false });
  progress.hidden = true;
  el('play-app').hidden = false;
}

function wire() {
  el('play-toggle').addEventListener('click', () => {
    if (app.timer !== null) pause();
    else play();
  });
  el('play-step').addEventListener('click', () => {
    pause();
    if (app.viewing === currentSeason()) playOne();
  });
  for (const button of document.querySelectorAll('.speed')) {
    button.addEventListener('click', () => {
      app.speed = Number(button.getAttribute('data-speed'));
      for (const other of document.querySelectorAll('.speed')) {
        other.classList.toggle('chosen', other === button);
      }
      if (app.timer !== null) { pause(); play(); }
    });
  }
  for (const button of document.querySelectorAll('.run-n')) {
    button.addEventListener('click', () => {
      pause();
      runRemaining = Number(button.getAttribute('data-run'));
      play();
    });
  }
  for (const box of document.querySelectorAll('input[name="play-stop"]')) {
    box.addEventListener('change', () => {
      if (box.checked) app.stopOn.add(box.value);
      else app.stopOn.delete(box.value);
    });
  }

  el('play-season').addEventListener('input', (event) => {
    pause();
    app.viewing = Number(event.target.value);
    el('play-season-label').textContent = `season ${app.viewing}`;
    el('play-undo').disabled = app.viewing >= currentSeason() || app.viewing < app.committedSeason;
  });

  el('play-undo').addEventListener('click', async () => {
    const target = app.viewing;
    const losing = currentSeason() - target;
    if (losing <= 0) return;
    const ok = window.confirm(
      `Undo to season ${target}? This discards ${losing} season(s) played after it,`
      + ' and cannot be undone.',
    );
    if (!ok) return;
    await rewindTo(target);
  });

  el('feed-filter').addEventListener('change', (event) => {
    app.filter = event.target.value;
    applyFilter();
  });

  document.addEventListener('click', (event) => {
    const houseButton = event.target.closest('[data-house]');
    if (houseButton) {
      showHouse(houseButton.getAttribute('data-house'));
      return;
    }
    const path = event.target.closest('#map-fills path');
    if (path) {
      const house = app.world.state.holderOfRiding(path.getAttribute('data-fed'));
      if (house) showHouse(house);
      else {
        el('panel-body').innerHTML =
          `<h3>${escapeHtml(path.getAttribute('data-riding'))}</h3>`
          + '<p class="meta">Unclaimed.</p>';
        el('panel').hidden = false;
      }
    }
  });
  el('panel-close').addEventListener('click', () => { el('panel').hidden = true; });

  const viewToggle = el('view-toggle');
  const map = el('map');
  viewToggle.addEventListener('click', () => {
    const showingSouth = map.getAttribute('viewBox') === map.getAttribute('data-view-south');
    map.setAttribute(
      'viewBox',
      showingSouth ? map.getAttribute('data-view-full') : map.getAttribute('data-view-south'),
    );
    el('map-borders').setAttribute(
      'stroke-width',
      showingSouth ? map.getAttribute('data-stroke-full') : map.getAttribute('data-stroke-south'),
    );
    viewToggle.textContent = showingSouth ? 'Show the south' : 'Show the north';
  });

  wireIntervene();
}

// Rewind by replaying: the engine is deterministic, so the cheapest correct
// undo is to load the published world again and play forward to the target.
// Keeping a full state snapshot per season would be faster and would put a
// hundred megabytes in a phone's memory over a long game.
async function rewindTo(target) {
  pause();
  const progress = el('load-progress');
  progress.hidden = false;
  progress.textContent = `Rewinding to season ${target}…`;
  el('play-app').hidden = true;

  const response = await fetch('data/world.json');
  const committed = await response.json();
  const world = new World({
    state: WorldState.load(committed, app.map),
    rules: app.rules,
    worldSeed: committed.world_seed,
  });
  const records = [];
  while (world.seasonNo < target) records.push(world.runSeason());

  app.world = world;
  app.history = records.map((record) => ({ season: record.season, record }));
  app.viewing = world.seasonNo;
  el('feed').innerHTML = '';
  for (const record of records.slice(-60)) {
    appendFeed(record.season, record.chronicle, {});
  }
  indexPaths();
  renderAll({ flash: false });
  await save();
  progress.hidden = true;
  el('play-app').hidden = false;
}

// ------------------------------------------------------------ intervening --

function wireIntervene() {
  const opSelect = el('iv-op');
  if (!opSelect) return;

  const showFields = () => {
    const chosen = opSelect.value;
    for (const field of document.querySelectorAll('.iv-for')) {
      const applies = (field.getAttribute('data-for') || '').split(' ');
      field.hidden = !applies.includes(chosen);
    }
    el('iv-house').closest('.field').hidden = chosen === 'grant_house';
  };
  opSelect.addEventListener('change', showFields);
  showFields();

  el('iv-apply').addEventListener('click', () => {
    const box = el('iv-status');
    const chosen = opSelect.value;
    const house = el('iv-house').value;
    const reason = el('iv-reason').value.trim();
    let operation;
    if (chosen === 'set_objective' || chosen === 'veto_objective') {
      operation = { op: chosen, house, objective: el('iv-objective').value, reason };
    } else if (chosen === 'force_action') {
      operation = { op: chosen, house, action: el('iv-action').value, reason };
    } else if (chosen === 'adjust_stat') {
      operation = {
        op: chosen, house, stat: el('iv-stat').value,
        delta: Number(el('iv-delta').value), reason,
      };
    } else if (chosen === 'set_clock') {
      operation = {
        op: chosen, house, personal_year: Number(el('iv-year').value),
        basis: reason || 'set in the browser',
      };
    } else if (chosen === 'relation') {
      operation = {
        op: chosen, house_a: house, house_b: el('iv-other').value,
        marker: el('iv-marker').value, text: reason || 'recorded in the browser',
      };
    } else {
      operation = {
        op: 'grant_house', riding: el('iv-riding').value.trim(),
        community: el('iv-community').value, rank: el('iv-rank').value,
        tag: el('iv-tag').value, reason,
      };
    }

    try {
      pause();
      const title = `Director: ${chosen.split('_').join(' ')}`;
      app.world.intervene([operation], title);
      const feedLine = chosen === 'grant_house'
        ? `The director grants a house at ${operation.riding}.`
        : `The director applies ${chosen.split('_').join(' ')} to ${operation.house || house}.`;
      const item = document.createElement('li');
      item.className = 'feed-season feed-director';
      item.innerHTML = `<h3>Season ${currentSeason()} · director</h3><p>${escapeHtml(feedLine)}</p>`;
      el('feed').prepend(item);
      renderAll({ flash: true });
      save();
      box.hidden = false;
      box.className = 'status-box good';
      box.textContent = 'Applied to this browser\\'s game.';
    } catch (error) {
      box.hidden = false;
      box.className = 'status-box bad';
      box.textContent = error.message;
    }
  });
}

boot().catch((error) => {
  const progress = el('load-progress');
  progress.hidden = false;
  progress.className = 'meta bad';
  progress.textContent = `The game could not start: ${error.message}`;
});
"""
