r"""The Replay page's JavaScript (archive/<name>/replay.html), as one module.

The page steps through a frozen game one turn at a time as the story layer's
dispatch (docs/STORY_DESIGN.md §3.2). The story layer is web/story/, copied to
the archived site's story/ on export; the typed beats are hoc/export/beats.py's
data/beats/, fetched a chunk at a time as the reader reaches them.

A raw string, so a backslash written here reaches the browser as written;
tests/test_js_syntax.py runs `node --check` over the result.
"""

REPLAY_JS = r"""// A frozen game, told one turn at a time.
//
// Generated by hoc/export/replay_js.py. The story layer is ./story/ (web/story/
// on export); the beats are ./data/beats/, typed from the game's record by
// hoc/export/beats.py and fetched a chunk at a time as they are needed.

import { Story } from './story/dispatch.js';
import { houseStyle } from './story/text.js';
import {
  MapCamera, afootHtml, dispatchHtml, escapeHtml, pauseReason, plansHtml, readStored, recordHtml,
  storylineHtml, stripHtml, writeStored,
} from './story/view.js';

const SCENARIO = __SCENARIO__;
const FOLLOW_KEY = `hoc-story-follow:${SCENARIO}`;
const UNCLAIMED_FILL = '__UNCLAIMED_FILL__';
const AUTO_MS = 1600;

const el = (id) => document.getElementById(id);

const app = {
  index: null,
  weights: null,
  chunks: new Map(),
  story: null,
  turn: 0,
  follow: null,
  auto: null,
  busy: false,
  camera: null,
  paths: [],
  styles: {},
  // The storyline open in the Afoot panel, if any.
  afoot: null,
};

async function fetchJson(url) {
  const response = await fetch(url);
  if (!response.ok) throw new Error(`${url}: HTTP ${response.status}`);
  return response.json();
}

// The chunk holding `turn`, fetched the first time it is needed: the turn's
// beats, and its prestige where the record carries it (rules 1.0).
async function turnData(turn) {
  const entry = app.index.chunks.find((c) => c.first <= turn && turn <= c.last);
  if (!entry) return { beats: [], prestige: null, plans: null };
  if (!app.chunks.has(entry.file)) {
    app.chunks.set(entry.file, fetchJson(`data/beats/${entry.file}`));
  }
  const chunk = await app.chunks.get(entry.file);
  return {
    beats: chunk.turns[String(turn)] || [],
    prestige: (chunk.prestige && chunk.prestige[String(turn)]) || null,
    // Rules 1.0 `schemes`: every public scheme as the turn left them.
    plans: chunk.plans ? (chunk.plans[String(turn)] || []) : null,
  };
}

function colourOf(house) {
  const info = app.index.houses[house];
  return info && info.colour ? info.colour : null;
}

function unitName() {
  return app.index.unit === 'turn' ? 'turn' : 'season';
}

function reset() {
  app.story = new Story({
    weights: app.weights,
    baseline: app.index.baseline,
    follow: app.follow,
    unit: unitName(),
    styleOf: (house) => app.styles[house] || null,
    ridings: app.index.ridings || {},
    watch: Boolean(app.index.succession_watch),
  });
  app.turn = 0;
}

async function stepTo(target) {
  let last = null;
  while (app.turn < target) {
    const { beats, prestige, plans } = await turnData(app.turn + 1);
    last = app.story.step(app.turn + 1, beats, { prestige, plans });
    app.turn += 1;
  }
  return last;
}

function paint() {
  const owners = app.story.board.owners;
  for (const path of app.paths) {
    const house = owners[path.getAttribute('data-fed')];
    path.setAttribute('fill', (house && colourOf(house)) || UNCLAIMED_FILL);
  }
}

// Where to point the camera: the headline's ridings, or, for a beat that moved
// none (a quarrel, a marriage), every riding its houses hold.
function focusOf(d) {
  if (!d || d.quiet) return [];
  if (d.zoom.length) return d.zoom;
  const houses = new Set(d.headline.beat.houses || []);
  return Object.entries(app.story.board.owners)
    .filter(([, house]) => houses.has(house))
    .map(([fed]) => fed);
}

function renderLabel() {
  const total = app.index.turns;
  el('story-turn').textContent = app.turn === 0
    ? `before ${unitName()} 1 of ${total}`
    : `${unitName()} ${app.turn} of ${total}`;
  el('story-next').disabled = app.turn >= total;
}

// The Afoot panel: open storylines; the chosen one's beats, and its houses
// marked on the map.
function renderAfoot() {
  // Plans afoot, above Afoot, for a record that carries schemes (rules 1.0).
  if (app.index.schemes) {
    el('story-plans').hidden = false;
    el('story-plans-list').innerHTML = plansHtml(app.story.plansAfoot() || [], { unit: unitName() });
  }
  const list = app.story.afoot();
  if (app.afoot && !app.story.lines.of(app.afoot)) app.afoot = null;
  el('story-afoot-list').innerHTML = afootHtml(list, { unit: unitName(), selected: app.afoot });
  const told = app.afoot ? app.story.tell(app.afoot) : null;
  el('story-afoot-detail').innerHTML = told
    ? storylineHtml(told, { unit: unitName(), link: (turn) => `#${unitName()}-${turn}` })
    : '';
  const houses = new Set(told ? told.houses : []);
  const owners = app.story.board.owners;
  for (const path of app.paths) {
    path.classList.toggle('afoot', houses.has(owners[path.getAttribute('data-fed')]));
  }
}

function show(d, { zoom = true } = {}) {
  paint();
  renderLabel();
  renderAfoot();
  el('story-strip').innerHTML = stripHtml(d ? d.standings : app.story.still(), { colourOf, follow: app.follow });
  if (!d) {
    el('story-dispatch').innerHTML =
      `<p class="dispatch-quiet">Press <b>Next ${unitName()}</b> to begin, or <b>Auto</b> to let it run.</p>`;
    el('story-record-lines').innerHTML = '';
    return;
  }
  el('story-dispatch').innerHTML = dispatchHtml(d, { unit: unitName() });
  el('story-record-lines').innerHTML = recordHtml(d);
  if (zoom && app.camera) app.camera.focus(focusOf(d));
}

async function next() {
  if (app.turn >= app.index.turns) return null;
  const d = await stepTo(app.turn + 1);
  show(d);
  return d;
}

function note(text) {
  const box = el('story-note');
  box.hidden = !text;
  box.textContent = text || '';
}

function stopAuto(reason = '') {
  if (app.auto !== null) clearTimeout(app.auto);
  app.auto = null;
  el('story-auto').textContent = 'Auto';
  el('story-auto').classList.remove('playing');
  note(reason);
}

function startAuto() {
  note('');
  el('story-auto').textContent = 'Pause';
  el('story-auto').classList.add('playing');
  const tick = async () => {
    const d = await guarded(next);
    if (app.auto === null) return;
    if (!d) { stopAuto(`The end of the record: ${unitName()} ${app.index.turns}.`); return; }
    if (d.pause) {
      stopAuto(pauseReason(d));
      return;
    }
    app.auto = setTimeout(tick, AUTO_MS);
  };
  app.auto = setTimeout(tick, 0);
}

// One thing at a time: a press while a chunk is loading is ignored rather than
// queued, so Next never skips a turn.
async function guarded(fn) {
  if (app.busy) return null;
  app.busy = true;
  try {
    return await fn();
  } catch (error) {
    stopAuto(`Could not load the record: ${error.message}`);
    return null;
  } finally {
    app.busy = false;
  }
}

async function goTo(target) {
  const turn = Math.max(0, Math.min(app.index.turns, target));
  await guarded(async () => {
    if (turn < app.turn || turn === 0) reset();
    const d = turn === 0 ? null : await stepTo(turn);
    show(d, { zoom: false });
  });
}

function renderFollow() {
  const select = el('story-follow');
  const names = Object.keys(app.index.houses).sort((a, b) => (a < b ? -1 : a > b ? 1 : 0));
  select.innerHTML = '<option value="">no one</option>'
    + names.map((h) => `<option>${escapeHtml(h)}</option>`).join('');
  select.value = app.follow && names.includes(app.follow) ? app.follow : '';
  if (!select.value) app.follow = null;
}

// replay.html#season-88 (or #turn-2) opens the replay at that turn: the
// Storylines page links each beat here.
function hashTurn() {
  const match = /^#(?:season|turn)-(\d+)$/.exec(window.location.hash);
  return match ? Number(match[1]) : null;
}

function wire() {
  window.addEventListener('hashchange', () => {
    const turn = hashTurn();
    if (turn !== null) { stopAuto(); goTo(turn); }
  });
  el('story-afoot-list').addEventListener('click', (event) => {
    const button = event.target.closest('[data-storyline]');
    if (!button) return;
    const id = button.getAttribute('data-storyline');
    app.afoot = app.afoot === id ? null : id;
    renderAfoot();
  });
  el('story-next').addEventListener('click', () => { stopAuto(); guarded(next); });
  el('story-auto').addEventListener('click', () => {
    if (app.auto !== null) stopAuto();
    else startAuto();
  });
  el('story-start').addEventListener('click', () => { stopAuto(); goTo(0); });
  el('story-goto').addEventListener('submit', (event) => {
    event.preventDefault();
    stopAuto();
    goTo(Number(el('story-goto-turn').value) || 0);
  });
  // Following changes the weights and so the headlines, never the game: the
  // story is told again from the start to where the reader stands.
  el('story-follow').addEventListener('change', (event) => {
    app.follow = event.target.value || null;
    writeStored(FOLLOW_KEY, app.follow);
    stopAuto();
    const at = app.turn;
    guarded(async () => {
      reset();
      show(at === 0 ? null : await stepTo(at), { zoom: false });
    });
  });
  const map = el('map');
  const toggle = el('view-toggle');
  toggle.addEventListener('click', () => {
    if (app.camera) app.camera.reset();
    const south = toggle.getAttribute('data-showing') !== 'full';
    map.setAttribute('viewBox', map.getAttribute(south ? 'data-view-full' : 'data-view-south'));
    el('map-borders').setAttribute(
      'stroke-width', map.getAttribute(south ? 'data-stroke-full' : 'data-stroke-south'),
    );
    toggle.setAttribute('data-showing', south ? 'full' : 'south');
    toggle.textContent = south ? 'Show the south' : 'Show the north';
  });
}

async function boot() {
  try {
    [app.index, app.weights] = await Promise.all([
      fetchJson('data/beats/index.json'),
      fetchJson('story/weights.json'),
    ]);
  } catch (error) {
    el('story-load').textContent = `The replay could not be loaded (${error.message}).`;
    return;
  }
  app.paths = [...document.querySelectorAll('#map-fills path')];
  for (const [house, info] of Object.entries(app.index.houses)) {
    app.styles[house] = houseStyle({ house, ...info });
  }
  app.camera = new MapCamera(el('map'), { borders: el('map-borders') });
  app.follow = readStored(FOLLOW_KEY);
  el('story-goto-turn').max = String(app.index.turns);
  renderFollow();
  reset();
  wire();
  show(null);
  el('story-load').hidden = true;
  el('story-app').hidden = false;
  const start = hashTurn();
  if (start !== null) goTo(start);
}

boot();
"""


STORYLINES_JS = r"""// Every storyline of a frozen game, told top to bottom.
//
// Generated by hoc/export/replay_js.py. Built here, in the browser, from the
// same beat data the Replay reads, by the same story layer (./story/): the
// game is replayed as dispatches and its storylines listed by type. Nothing
// about storylines is computed in Python.

import { Story } from './story/dispatch.js';
import { STORYLINE_TYPES } from './story/storylines.js';
import { houseStyle } from './story/text.js';
import { escapeHtml, storylineHtml } from './story/view.js';

const HEADINGS = {
  rivalry: 'Rivalries', union: 'Unions', succession: 'Succession questions',
  rise: 'Rises', decline: 'Declines', frontier: 'Frontiers',
};

const el = (id) => document.getElementById(id);

async function fetchJson(url) {
  const response = await fetch(url);
  if (!response.ok) throw new Error(`${url}: HTTP ${response.status}`);
  return response.json();
}

async function boot() {
  let index;
  let weights;
  let chunks;
  try {
    [index, weights] = await Promise.all([
      fetchJson('data/beats/index.json'),
      fetchJson('story/weights.json'),
    ]);
    chunks = await Promise.all(index.chunks.map((c) => fetchJson(`data/beats/${c.file}`)));
  } catch (error) {
    el('lines-load').textContent = `The storylines could not be loaded (${error.message}).`;
    return;
  }
  const byTurn = {};
  const prestige = {};
  for (const chunk of chunks) {
    Object.assign(byTurn, chunk.turns);
    Object.assign(prestige, chunk.prestige || {});
  }
  const styles = {};
  for (const [house, info] of Object.entries(index.houses)) styles[house] = houseStyle({ house, ...info });
  const unit = index.unit === 'turn' ? 'turn' : 'season';
  const story = new Story({
    weights, baseline: index.baseline, unit,
    styleOf: (house) => styles[house] || null, ridings: index.ridings || {},
    watch: Boolean(index.succession_watch),
  });
  for (let turn = 1; turn <= index.turns; turn += 1) {
    story.step(turn, byTurn[String(turn)] || [], { prestige: prestige[String(turn)] || null });
  }

  const all = story.lines.all;
  const sections = [];
  const contents = [];
  for (const type of STORYLINE_TYPES) {
    const lines = all.filter((s) => s.type === type).sort((a, b) => a.opened - b.opened || (a.id < b.id ? -1 : 1));
    if (!lines.length) continue;
    contents.push(`<a href="#type-${type}">${HEADINGS[type]} (${lines.length})</a>`);
    const items = lines.map((s) => {
      const told = story.tell(s.id);
      const end = s.state === 'closed' ? `${unit}s ${s.opened}–${s.closed}` : `since ${unit} ${s.opened}`;
      return `<details class="storyline" id="${escapeHtml(s.id)}"><summary>`
        + `<span class="storyline-title">${escapeHtml(told.name)}</span>`
        + `<span class="meta"> ${told.beats.length} beat${told.beats.length === 1 ? '' : 's'} &middot; ${end}`
        + ` &middot; ${escapeHtml(s.state === 'closed' ? s.outcome : s.state)}</span></summary>`
        + storylineHtml(told, { unit, link: (turn) => `replay.html#${unit}-${turn}` })
        + '</details>';
    });
    sections.push(`<section id="type-${type}" class="storyline-type"><h2>${HEADINGS[type]}`
      + ` <span class="count">${lines.length}</span></h2>${items.join('')}</section>`);
  }
  const closed = all.filter((s) => s.state === 'closed').length;
  el('lines-summary').textContent = `${all.length} storylines over ${index.turns} ${unit}s:`
    + ` ${closed} closed, ${all.length - closed} still open when the record ends.`;
  el('lines-types').innerHTML = contents.join(' &middot; ');
  el('lines-body').innerHTML = sections.join('') || '<p class="meta">This game has no storylines.</p>';
  el('lines-load').hidden = true;
  el('lines-app').hidden = false;
  if (window.location.hash) {
    const target = document.getElementById(window.location.hash.slice(1));
    if (target && target.tagName === 'DETAILS') target.open = true;
    if (target) target.scrollIntoView();
  }
}

boot();
"""
