r"""The Replay pages' JavaScript and the map view's stylesheet.

REPLAY_JS is the Replay (replay.html, Phase V): the game on a map that fills the
screen, its events as marks with cards, the camera following the headline
(docs/STORY_DESIGN.md §3.6). REPLAY_TEXT_JS is the Replay (text)
(replay-text.html): the same game one turn at a time as the story layer's
dispatch in a column (§3.2). The story layer is web/story/, copied to
the archived site's story/ on export; the typed beats are hoc/export/beats.py's
data/beats/, fetched a chunk at a time as the reader reaches them.

A raw string, so a backslash written here reaches the browser as written;
tests/test_js_syntax.py runs `node --check` over the result.
"""

REPLAY_JS = r"""// The Replay: a game on the map (docs/STORY_DESIGN.md §3.6, Phase V).
//
// Generated by hoc/export/replay_js.py (REPLAY_JS). The map fills the screen.
// Each turn the story layer (./story/) tells the dispatch; marks.js says where
// it happened and how it is drawn; camera.js frames it, leaving room for the
// headline's card, until a gesture frees the camera. The beats are
// ./data/beats/, fetched a chunk at a time; each house's seat over the game
// and the jurisdictions by year are ./data/beats/atlas.json; the fuller map is
// ./data/map-detail.json, fetched the first time the camera comes close.

import { Story } from './story/dispatch.js';
import { Namer, houseStyle, rankForm, readerNames, surnameOf } from './story/text.js';
import {
  afootHtml, chapterHtml, dispatchHtml, escapeHtml, pauseReason, plansHtml, readStored,
  reckoningHtml, recordHtml, storylineHtml, stripHtml, writeStored,
} from './story/view.js';
import { MarkContext, marksFor, seatsAt } from './story/marks.js';
import {
  Camera, Gestures, clampView, flight, frameView, freeRect, limitsFor, panBy, placeCard,
  toScreen, unionBounds, viewAt, zoomAt,
} from './story/camera.js';
import { PROVINCES } from './story/storylines.js';

const SCENARIO = __SCENARIO__;
const FOLLOW_KEY = `hoc-story-follow:${SCENARIO}`;
const SPEED_KEY = 'hoc-story-speed';
const UNCLAIMED_FILL = '__UNCLAIMED_FILL__';
const DETAIL_BELOW = __DETAIL_BELOW__;
const SPEEDS = [{ label: '1×', ms: 3600 }, { label: '2×', ms: 1900 }, { label: '4×', ms: 950 }];
const FLIGHT_MS = 850;
const SVGNS = 'http://www.w3.org/2000/svg';

const el = (id) => document.getElementById(id);
const reduced = () => Boolean(globalThis.matchMedia && matchMedia('(prefers-reduced-motion: reduce)').matches);

const app = {
  index: null,
  weights: null,
  atlas: { seats: {} },
  chunks: new Map(),
  story: null,
  turn: 0,
  d: null,
  layout: null,
  plans: null,
  plansBefore: null,
  follow: null,
  afoot: null,
  auto: null,
  busy: false,
  speed: 0,
  styles: {},
  names: new Map(),
  ridingIds: {},
  paths: new Map(),
  boxes: new Map(),
  points: new Map(),
  world: null,
  screen: { w: 1, h: 1 },
  view: null,
  committed: null,
  camera: new Camera(),
  gestures: new Gestures(),
  gesturing: false,
  flying: null,
  card: null,
  detail: 'none',
  downTarget: null,
};

// ------------------------------------------------------------- the record --

async function fetchJson(url) {
  const response = await fetch(url);
  if (!response.ok) throw new Error(`${url}: HTTP ${response.status}`);
  return response.json();
}

async function turnData(turn) {
  const entry = app.index.chunks.find((c) => c.first <= turn && turn <= c.last);
  if (!entry) return { beats: [], prestige: null, plans: null };
  if (!app.chunks.has(entry.file)) app.chunks.set(entry.file, fetchJson(`data/beats/${entry.file}`));
  const chunk = await app.chunks.get(entry.file);
  return {
    beats: chunk.turns[String(turn)] || [],
    prestige: (chunk.prestige && chunk.prestige[String(turn)]) || null,
    plans: chunk.plans ? (chunk.plans[String(turn)] || []) : null,
  };
}

function calendar() {
  return app.index.calendar || null;
}

function unitName() {
  if (calendar()) return 'year';
  return app.index.unit === 'turn' ? 'turn' : 'season';
}

function yearOf(turn) {
  return calendar() ? calendar().start_year + turn - 1 : null;
}

function colourOf(house) {
  const info = app.index.houses[house];
  return info && info.colour ? info.colour : null;
}

// "Surname of Place": a house's peerage less its rank word, which is how the
// standings tell a surname from a designation.
function titleOf(house) {
  const s = app.styles[house];
  return s ? s.title : surnameOf(house);
}

function reset() {
  app.story = new Story({
    weights: app.weights,
    baseline: app.index.baseline,
    follow: app.follow,
    unit: unitName(),
    styleOf: (house) => app.styles[house] || null,
    ridings: app.index.ridings || {},
    watch: Boolean(app.index.succession_watch),
    calendar: calendar(),
    reckoning: app.index.reckoning || null,
  });
  app.turn = 0;
  app.d = null;
  app.plans = null;
  app.plansBefore = null;
}

async function stepTo(target) {
  let last = null;
  while (app.turn < target) {
    const { beats, prestige, plans } = await turnData(app.turn + 1);
    app.plansBefore = app.plans;
    last = app.story.step(app.turn + 1, beats, { prestige, plans });
    if (plans !== null) app.plans = plans;
    app.turn += 1;
  }
  return last;
}

// --------------------------------------------------------------- geometry --

function boxOf(fed) {
  if (app.boxes.has(fed)) return app.boxes.get(fed);
  const path = app.paths.get(fed);
  let box = null;
  if (path && typeof path.getBBox === 'function') {
    const b = path.getBBox();
    if (b.width || b.height) box = [b.x, b.y, b.width, b.height];
  }
  app.boxes.set(fed, box);
  return box;
}

// A point inside a riding to put its mark on: the middle of its box if that
// is inside it, else the nearest point inside on a grid over the box.
function pointOf(fed) {
  if (app.points.has(fed)) return app.points.get(fed);
  const box = boxOf(fed);
  if (!box) return null;
  const [x, y, w, h] = box;
  const middle = [x + w / 2, y + h / 2];
  const path = app.paths.get(fed);
  const inside = ([px, py]) => {
    try {
      return path.isPointInFill(new DOMPoint(px, py));
    } catch (error) {
      return true;
    }
  };
  let best = middle;
  if (!inside(middle)) {
    let bestD = Infinity;
    for (let i = 1; i < 10; i += 1) {
      for (let j = 1; j < 10; j += 1) {
        const p = [x + (w * i) / 10, y + (h * j) / 10];
        const dd = (p[0] - middle[0]) ** 2 + (p[1] - middle[1]) ** 2;
        if (dd < bestD && inside(p)) { best = p; bestD = dd; }
      }
    }
  }
  app.points.set(fed, best);
  return best;
}

function boundsOf(feds) {
  return unionBounds(feds.map(boxOf));
}

function screenOf(fed) {
  const p = fed ? pointOf(fed) : null;
  return p ? toScreen(app.view, app.screen, p) : null;
}

// ------------------------------------------------------------------ view --

function bars() {
  const top = document.querySelector('.mv-top').getBoundingClientRect();
  const bottom = document.querySelector('.mv-bottom').getBoundingClientRect();
  return { top: Math.round(top.bottom), bottom: Math.round(app.screen.h - bottom.top) };
}

function measure() {
  const stage = el('mv-stage');
  app.screen = { w: Math.max(1, stage.clientWidth), h: Math.max(1, stage.clientHeight) };
}

function limits() {
  return limitsFor(app.world, app.screen, { minW: 3 });
}

// Show `view`: during a gesture or a flight the drawn map is moved by a CSS
// transform, which the compositor does cheaply; the SVG's own viewBox is set
// (committed) when the movement ends. Marks and the card are redrawn every
// time, in screen pixels, so they keep their size.
function applyView(view, { commit = false } = {}) {
  app.view = view;
  const c = app.committed;
  if (!c || commit) {
    commitView();
  } else {
    const k = app.screen.w / view.w;
    const s = c.w / view.w;
    const tx = (c.x - view.x) * k;
    const ty = (c.y - view.y) * k;
    el('mv-layer').style.transform = `translate(${tx.toFixed(2)}px, ${ty.toFixed(2)}px) scale(${s.toFixed(5)})`;
    if (s > 3 || s < 0.4) commitView();
  }
  drawMarks();
  placeOpenCard();
  if (view.w < DETAIL_BELOW) loadDetail();
}

function commitView() {
  const v = app.view;
  app.committed = { ...v };
  const map = el('map');
  map.setAttribute('viewBox', `${v.x.toFixed(3)} ${v.y.toFixed(3)} ${v.w.toFixed(3)} ${v.h.toFixed(3)}`);
  el('mv-layer').style.transform = '';
  // The closed-land hatching keeps its size on screen.
  const pattern = el('mv-closed');
  if (pattern) {
    const size = (7 * v.w) / app.screen.w;
    pattern.setAttribute('width', size.toFixed(4));
    pattern.setAttribute('height', size.toFixed(4));
    pattern.querySelector('path').setAttribute('d', `M0,0 L${size.toFixed(4)},${size.toFixed(4)}`);
  }
}

function cancelFlight() {
  if (app.flying !== null) cancelAnimationFrame(app.flying);
  app.flying = null;
}

function fly(target) {
  cancelFlight();
  const to = clampView(target, app.world, app.screen, limits());
  const from = app.view;
  if (!from || reduced()) {
    applyView(to, { commit: true });
    return;
  }
  const start = performance.now();
  const frame = (now) => {
    const t = Math.min(1, (now - start) / FLIGHT_MS);
    if (t < 1) {
      applyView(flight(from, to, t));
      app.flying = requestAnimationFrame(frame);
    } else {
      app.flying = null;
      applyView(to, { commit: true });
    }
  };
  app.flying = requestAnimationFrame(frame);
}

function setFree(free) {
  el('mv-recentre').hidden = !free;
}

function takeCamera() {
  cancelFlight();
  if (app.camera.gesture()) setFree(true);
}

// The view a turn frames: the headline's ground in the part of the screen its
// card leaves free.
function frameFor(layout) {
  if (!layout || !layout.frame.length) return null;
  const bounds = boundsOf(layout.frame);
  if (!bounds) return null;
  const b = bars();
  const rect = freeRect(app.screen, { top: b.top + 8, bottom: b.bottom + 8, card: true });
  return frameView(bounds, app.screen, rect, app.world, { limits: limits() });
}

// Before the first turn: the land open in the first year where the game has
// a calendar (Confederation's four provinces), else the south of the map.
function homeView() {
  let ground = null;
  if (calendar() && app.atlas.jurisdictions) {
    const year = calendar().start_year;
    ground = boundsOf([...app.paths.keys()].filter((fed) => app.atlas.jurisdictions[fed] && !closedAt(fed, year)));
  }
  if (!ground) ground = el('map').getAttribute('data-view-south').split(/[\s,]+/).map(Number);
  const b = bars();
  const rect = freeRect(app.screen, { top: b.top + 8, bottom: b.bottom + 8, card: false });
  return frameView(ground, app.screen, rect, app.world, { pad: 0.04, minGround: 1, limits: limits() });
}

// ------------------------------------------------------------- the board --

function closedAt(fed, year) {
  const spans = app.atlas.jurisdictions && app.atlas.jurisdictions[fed];
  if (!spans || year === null) return false;
  const span = spans.find(([from, to]) => from <= year && (to === null || year <= to));
  return Boolean(span) && span[4] !== 'Canada';
}

function jurisdictionAt(fed, year) {
  const spans = app.atlas.jurisdictions && app.atlas.jurisdictions[fed];
  if (spans && year !== null) {
    const span = spans.find(([from, to]) => from <= year && (to === null || year <= to));
    if (span) {
      return span[4] === 'Canada' ? `${span[2]}, a ${span[3]} of Canada` : `${span[2]}, a ${span[3]} under ${span[4]}`;
    }
  }
  return PROVINCES[String(fed).slice(0, 2)] || null;
}

function paint() {
  const owners = app.story.board.owners;
  const year = calendar() ? yearOf(Math.max(1, app.turn)) : null;
  for (const [fed, path] of app.paths) {
    const house = owners[fed];
    let fill = (house && colourOf(house)) || UNCLAIMED_FILL;
    if (!house && closedAt(fed, year)) fill = 'url(#mv-closed)';
    path.style.fill = fill;
    path.classList.toggle('closed', fill === 'url(#mv-closed)');
  }
}

// Outlines drawn in the map's own coordinates, at a stroke width that does
// not scale: the followed house's ridings, and the ridings the marks name.
function drawOutlines() {
  const group = el('mv-outlines');
  group.textContent = '';
  const add = (fed, cls) => {
    const path = app.paths.get(fed);
    if (!path) return;
    const o = document.createElementNS(SVGNS, 'path');
    o.setAttribute('d', path.getAttribute('d'));
    o.setAttribute('class', cls);
    o.setAttribute('vector-effect', 'non-scaling-stroke');
    group.appendChild(o);
  };
  if (app.follow && app.story) {
    for (const [fed, house] of Object.entries(app.story.board.owners)) {
      if (house === app.follow) add(fed, 'ol ol-follow');
    }
  }
  for (const m of (app.layout ? app.layout.marks : [])) {
    const cls = m.type === 'claim' ? (m.result ? 'ol ol-claim ol-resolved' : 'ol ol-claim')
      : m.type === 'accession' ? 'ol ol-open' : 'ol ol-mark';
    for (const fed of m.ridings) add(fed, cls);
  }
}

// ----------------------------------------------------------------- marks --

const GLYPHS = {
  found: '<path class="g-fill" d="M0,-8 L2.4,-2.6 L8,-2.4 L3.7,1.2 L5,7 L0,3.8 L-5,7 L-3.7,1.2 L-8,-2.4 L-2.4,-2.6 Z"/>',
  succeed: '<path class="g-line" d="M5.6,-3.6 A6.5,6.5 0 1,0 6.4,2.2"/><path class="g-fill" d="M3,-6.5 L7.6,-5 L5.6,-0.8 Z"/>',
  elevate: '<path class="g-fill" d="M-7,5 L-7,-3.5 L-3.5,0.5 L0,-6.5 L3.5,0.5 L7,-3.5 L7,5 Z"/>',
  fall: '<path class="g-line g-bold" d="M-5,-5 L5,5 M5,-5 L-5,5"/>',
  failed: '<circle class="g-line" r="5.5"/><path class="g-line" d="M-3.9,3.9 L3.9,-3.9"/>',
  dot: '<circle class="g-fill" r="3.5"/>',
  transfer: '<path class="g-line" d="M-6,-2.5 L5,-2.5 M2,-5.5 L5,-2.5 L2,0.5 M6,2.5 L-5,2.5 M-2,-0.5 L-5,2.5 L-2,5.5"/>',
  expand: '<path class="g-line g-bold" d="M-6,0 L6,0 M0,-6 L0,6"/>',
  claim: '<circle class="g-line" r="4.5"/><path class="g-line" d="M0,-8.5 L0,-4.5 M0,4.5 L0,8.5 M-8.5,0 L-4.5,0 M4.5,0 L8.5,0"/>',
  taken: '<path class="g-line g-bold" d="M-6,0 L-2,4.5 L6,-5"/>',
  held: '<path class="g-fill" d="M0,-7.5 L6.5,-4.8 L6.5,0 C6.5,4 3,6.7 0,8 C-3,6.7 -6.5,4 -6.5,0 L-6.5,-4.8 Z"/>',
  scheme: '<path class="g-line" d="M-6,0 L5,0 M1,-4 L5,0 L1,4"/>',
  match: '<circle class="g-line" cx="-2.8" r="4.2"/><circle class="g-line" cx="2.8" r="4.2"/>',
  bond: '<path class="g-line g-bold" d="M-6,-2.5 L6,-2.5 M-6,2.5 L6,2.5"/>',
  peace: '<path class="g-line g-bold" d="M-6,-2.5 L6,-2.5 M-6,2.5 L6,2.5"/>',
  strife: '<path class="g-fill" d="M2,-8 L-4.5,1.2 L-0.5,1.2 L-2.5,8 L4.5,-1.4 L0.5,-1.4 Z"/>',
  open: '<path class="g-line" d="M-4,7.5 L-4,-7"/><path class="g-fill" d="M-4,-7 L6.5,-4 L-4,-0.5 Z"/>',
  crisis: '<path class="g-fill" d="M0,-7 L7,6 L-7,6 Z"/>',
  lead: '<path class="g-fill" d="M0,-6 L6,5 L-6,5 Z"/>',
  resist: '<path class="g-fill" d="M0,6 L6,-5 L-6,-5 Z"/>',
  aside: '<circle class="g-line" r="3.5"/>',
};

function svgEl(name, attrs = {}) {
  const node = document.createElementNS(SVGNS, name);
  for (const [k, v] of Object.entries(attrs)) node.setAttribute(k, String(v));
  return node;
}

function line(layer, a, b, cls) {
  if (!a || !b) return;
  layer.appendChild(svgEl('line', {
    x1: a[0].toFixed(1), y1: a[1].toFixed(1), x2: b[0].toFixed(1), y2: b[1].toFixed(1), class: cls,
  }));
}

// A line from a seat to a target stops short of the target's badge, so its
// arrowhead is seen.
function shortened(a, b, by = 16) {
  const d = Math.hypot(b[0] - a[0], b[1] - a[1]);
  if (d <= by * 2) return b;
  return [b[0] - ((b[0] - a[0]) * by) / d, b[1] - ((b[1] - a[1]) * by) / d];
}

function badge(layer, at, glyph, { id = null, head = false, cls = '', small = false } = {}) {
  if (!at) return;
  const g = svgEl('g', {
    class: `mk ${cls}${head ? ' mk-head' : ''}${small ? ' mk-small' : ''}`,
    transform: `translate(${at[0].toFixed(1)},${at[1].toFixed(1)})`,
  });
  if (id) g.setAttribute('data-mark', id);
  const r = badgeRadius({ head, small });
  g.innerHTML = `<circle class="mk-hit" r="${small ? 14 : 22}"/><circle class="mk-bg" r="${r}"/>`
    + `<g class="mk-glyph"${small ? ' transform="scale(0.75)"' : ''}>${GLYPHS[glyph] || GLYPHS.dot}</g>`;
  layer.appendChild(g);
}

function badgeRadius({ head = false, small = false } = {}) {
  return small ? 8 : head ? 15 : 12.5;
}

// Where each mark's badge sits, in screen pixels.
function anchorOf(m) {
  if (m.type === 'bond' || m.type === 'strife') {
    const a = screenOf(m.from);
    const b = screenOf(m.to);
    if (a && b) return [(a[0] + b[0]) / 2, (a[1] + b[1]) / 2];
    return a || b;
  }
  if (m.type === 'crisis') {
    const points = [...m.camps.lead, ...m.camps.resist, ...m.camps.aside].map(screenOf).filter(Boolean);
    if (!points.length) return null;
    return [points.reduce((s, p) => s + p[0], 0) / points.length, points.reduce((s, p) => s + p[1], 0) / points.length];
  }
  if (m.type === 'accession') {
    const box = boundsOf(m.ridings);
    if (!box) return null;
    const centre = [box[0] + box[2] / 2, box[1] + box[3] / 2];
    let best = null;
    let bestD = Infinity;
    for (const fed of m.ridings) {
      const p = pointOf(fed);
      const d = p ? (p[0] - centre[0]) ** 2 + (p[1] - centre[1]) ** 2 : Infinity;
      if (d < bestD) { best = fed; bestD = d; }
    }
    return screenOf(best);
  }
  return screenOf(m.at || m.to || m.from);
}

// Badges never sit on one another: each, in order of importance, takes the
// nearest free spot around where it belongs, and a badge moved off its place
// keeps a short leader back to it.
const NUDGES = [[0, 0], [1, 0], [-1, 0], [0, -1], [0, 1], [1, -1], [-1, -1], [1, 1], [-1, 1],
  [2, 0], [-2, 0], [0, -2], [0, 2], [2, -1], [-2, -1], [2, 1], [-2, 1]];

function settle(placed, p, r) {
  if (!p) return null;
  for (const [i, j] of NUDGES) {
    const q = [p[0] + i * (2 * r + 3), p[1] + j * (2 * r + 3)];
    if (placed.every((o) => Math.hypot(o.x - q[0], o.y - q[1]) >= o.r + r + 2)) {
      placed.push({ x: q[0], y: q[1], r });
      return q;
    }
  }
  placed.push({ x: p[0], y: p[1], r });
  return p;
}

function overlaps(a, b) {
  return a.x0 < b.x1 && b.x0 < a.x1 && a.y0 < b.y1 && b.y0 < a.y1;
}

function drawMarks() {
  const layer = el('mv-marks');
  layer.setAttribute('width', app.screen.w);
  layer.setAttribute('height', app.screen.h);
  layer.innerHTML = '<defs>'
    + '<marker id="mv-arrow" viewBox="0 0 10 10" refX="8" refY="5" markerWidth="7" markerHeight="7" orient="auto-start-reverse">'
    + '<path d="M0,0 L10,5 L0,10 Z" class="mv-arrowhead"/></marker>'
    + '<marker id="mv-arrow-faint" viewBox="0 0 10 10" refX="8" refY="5" markerWidth="6" markerHeight="6" orient="auto-start-reverse">'
    + '<path d="M0,0 L10,5 L0,10 Z" class="mv-arrowhead-faint"/></marker></defs>';
  const layout = app.layout;
  if (!layout || !app.view) return;
  const lines = svgEl('g', { class: 'mv-lines' });
  const badges = svgEl('g', { class: 'mv-badges' });
  const labels = svgEl('g', { class: 'mv-labels' });
  layer.appendChild(lines);
  layer.appendChild(badges);
  layer.appendChild(labels);
  for (const s of layout.schemes) {
    const a = screenOf(s.from);
    const b = screenOf(s.to);
    if (a && b) {
      const end = shortened(a, b, 6);
      lines.appendChild(svgEl('line', {
        x1: a[0].toFixed(1), y1: a[1].toFixed(1), x2: end[0].toFixed(1), y2: end[1].toFixed(1),
        class: 'ln ln-intent', 'marker-end': 'url(#mv-arrow-faint)',
      }));
    }
  }
  // The lines first, between the true places.
  for (const m of layout.marks) {
    if (m.type === 'crisis') continue;
    const from = screenOf(m.from);
    const to = screenOf(m.to);
    if (!from || !to || m.from === m.to) continue;
    if (m.type === 'bond' || m.type === 'strife') {
      line(lines, from, to, 'ln ln-casing');
      line(lines, from, to, `ln ln-${m.type}`);
    } else if (m.type === 'claim' || m.type === 'scheme') {
      const end = shortened(from, to);
      line(lines, from, end, 'ln ln-casing');
      lines.appendChild(svgEl('line', {
        x1: from[0].toFixed(1), y1: from[1].toFixed(1), x2: end[0].toFixed(1), y2: end[1].toFixed(1),
        class: `ln ln-${m.type}`, 'marker-end': 'url(#mv-arrow)',
      }));
      lines.appendChild(svgEl('circle', { cx: from[0].toFixed(1), cy: from[1].toFixed(1), r: 4, class: 'ln-origin' }));
    }
  }
  // Then where every badge goes, most important first: the headline, the
  // other marks by weight, a fall, and last a crisis's many small camp marks.
  const placed = [];
  const items = [];
  for (const m of layout.marks) {
    if (m.type === 'crisis') continue;
    const r = badgeRadius({ head: m.headline });
    const true_ = anchorOf(m);
    items.push({ m, glyph: m.glyph, label: m.label, head: m.headline, cls: `mk-${m.type}`, true_, at: settle(placed, true_, r), r });
    if (m.fall) {
      const p = screenOf(m.fall);
      items.push({ m, glyph: 'fall', label: 'falls', head: false, cls: 'mk-seat', true_: p, at: settle(placed, p, 12.5), r: 12.5 });
    }
  }
  for (const m of layout.marks) {
    if (m.type !== 'crisis') continue;
    for (const [camp, seats] of [['lead', m.camps.lead], ['resist', m.camps.resist], ['aside', m.camps.aside]]) {
      for (const fed of seats) {
        const p = screenOf(fed);
        items.push({ m, glyph: camp, label: null, small: true, cls: `mk-${camp}`, true_: p, at: settle(placed, p, 8), r: 8 });
      }
    }
  }
  for (const it of items) {
    if (it.at && it.true_ && Math.hypot(it.at[0] - it.true_[0], it.at[1] - it.true_[1]) > 3) {
      line(lines, it.true_, it.at, 'ln ln-leader');
      lines.appendChild(svgEl('circle', { cx: it.true_[0].toFixed(1), cy: it.true_[1].toFixed(1), r: 2.5, class: 'ln-pin' }));
    }
  }
  // Drawn least important first, so the headline is on top.
  for (const it of [...items].reverse()) {
    badge(badges, it.at, it.glyph, { id: it.m.id, head: it.head, cls: it.cls, small: it.small });
  }
  // A label under a badge where it fits clear of every badge and label.
  const taken = placed.map((o) => ({ x0: o.x - o.r, x1: o.x + o.r, y0: o.y - o.r, y1: o.y + o.r }));
  for (const it of items) {
    if (!it.label || !it.at) continue;
    const size = it.head ? 12 : 11;
    const w = it.label.length * size * 0.56 + 6;
    const y = it.at[1] + it.r + size + 1;
    const rect = { x0: it.at[0] - w / 2, x1: it.at[0] + w / 2, y0: y - size, y1: y + 3 };
    const own = { x0: it.at[0] - it.r, x1: it.at[0] + it.r, y0: it.at[1] - it.r, y1: it.at[1] + it.r };
    if (taken.some((t) => overlaps(t, rect) && !(t.x0 === own.x0 && t.y0 === own.y0))) continue;
    taken.push(rect);
    const text = svgEl('text', {
      x: it.at[0].toFixed(1), y: y.toFixed(1), class: `mk-label${it.head ? ' mk-label-head' : ''}`,
    });
    text.textContent = it.label;
    labels.appendChild(text);
  }
}

// ----------------------------------------------------------------- cards --

function closeCard() {
  app.card = null;
  el('mv-card').hidden = true;
}

function markById(id) {
  return app.layout ? app.layout.marks.find((m) => m.id === id) : null;
}

function ridingCardHtml(fed) {
  const name = (app.index.ridings || {})[fed] || fed;
  const turn = app.turn;
  const year = calendar() ? yearOf(Math.max(1, turn)) : null;
  const board = app.story.board;
  const house = board.owners[fed];
  const when = calendar() ? `In ${year}` : turn ? `In ${unitName()} ${turn}` : 'Before the first turn';
  const where = jurisdictionAt(fed, year);
  let holder;
  if (house) {
    const namer = new Namer((h) => app.styles[h] || null, (h) => board.ranks[h] || 0);
    const s = app.styles[house];
    const rank = s ? rankForm(board.ranks[house] || 0, s.female) : null;
    const seat = seatsAt(app.atlas.seats, turn).get(house) === fed;
    holder = `<p class="mv-card-text">Held by <span class="swatch" style="background:${escapeHtml(colourOf(house) || '#bbb')}"></span>`
      + `<b>${escapeHtml(namer.style(house))}</b>${rank ? ` (rank: ${escapeHtml(rank)})` : ''}`
      + `${seat ? ', <b>its seat</b>' : ''}.</p>`;
  } else if (closedAt(fed, year)) {
    holder = '<p class="mv-card-text">Not yet under Canada: closed to every house.</p>';
  } else {
    holder = '<p class="mv-card-text">Unclaimed.</p>';
  }
  return `<p class="mv-card-kicker">${escapeHtml(when)}${where ? ` · ${escapeHtml(where)}` : ''}</p>`
    + `<h2 class="mv-card-title">${escapeHtml(name)}</h2>${holder}`;
}

function markCardHtml(m) {
  const d = app.d;
  if (m.headline && d && d.headline) {
    const kicker = d.kicker ? `<p class="mv-card-kicker">${escapeHtml(d.kicker.text)}</p>` : '';
    const previously = d.previously
      ? `<p class="mv-card-previously">Previously, ${escapeHtml(String(d.previously.year ?? `${unitName()} ${d.previously.turn}`))}:`
        + ` ${escapeHtml(d.previously.text)}</p>` : '';
    return `${kicker}<p class="mv-card-text mv-card-headline">${escapeHtml(d.headline.text)}</p>${previously}`;
  }
  const kind = m.kind.replace(/_/g, ' ');
  const camps = m.type === 'crisis'
    ? '<p class="mv-card-legend"><span class="lg lg-lead">▲ lead</span> <span class="lg lg-resist">▼ resist</span>'
      + ' <span class="lg lg-aside">○ aside</span></p>' : '';
  return `<p class="mv-card-kicker">${escapeHtml(kind)}</p><p class="mv-card-text">${escapeHtml(m.text)}</p>${camps}`;
}

function openCard(card) {
  app.card = card;
  const box = el('mv-card');
  let html = '';
  if (card.kind === 'riding') html = ridingCardHtml(card.fed);
  else {
    const m = markById(card.id);
    if (!m) { closeCard(); return; }
    html = markCardHtml(m);
  }
  box.innerHTML = '<button type="button" class="mv-card-close" aria-label="Close">×</button>' + html;
  box.hidden = false;
  placeOpenCard();
}

function placeOpenCard() {
  const box = el('mv-card');
  if (!app.card || box.hidden || !app.view) return;
  let anchor = null;
  if (app.card.kind === 'riding') {
    const p = screenOf(app.card.fed);
    if (p) anchor = { x: p[0], y: p[1], r: 10 };
  } else {
    const m = markById(app.card.id);
    if (m && m.type === 'crisis') {
      const pts = [...m.camps.lead, ...m.camps.resist, ...m.camps.aside].map(screenOf).filter(Boolean);
      if (pts.length) {
        const xs = pts.map((p) => p[0]);
        const ys = pts.map((p) => p[1]);
        const x0 = Math.min(...xs); const x1 = Math.max(...xs);
        const y0 = Math.min(...ys); const y1 = Math.max(...ys);
        anchor = { x: (x0 + x1) / 2, y: (y0 + y1) / 2, rx: (x1 - x0) / 2 + 10, ry: (y1 - y0) / 2 + 10 };
      }
    } else if (m) {
      const p = anchorOf(m);
      if (p) anchor = { x: p[0], y: p[1], r: m.headline ? 30 : 26 };
    }
  }
  const b = bars();
  const safe = { top: b.top + 6, bottom: b.bottom + 6, left: 8, right: 8 };
  if (!anchor) anchor = { x: app.screen.w / 2, y: b.top, r: 0 };
  // A mark off screen (free mode): the card docks at the nearest edge.
  anchor.x = Math.max(0, Math.min(app.screen.w, anchor.x));
  anchor.y = Math.max(0, Math.min(app.screen.h, anchor.y));
  const card = { w: box.offsetWidth, h: box.offsetHeight };
  const at = placeCard({ anchor, card, screen: app.screen, safe });
  box.style.transform = `translate(${Math.round(at.x)}px, ${Math.round(at.y)}px)`;
  box.setAttribute('data-side', at.side);
}

// --------------------------------------------------------------- showing --

function standing() {
  const board = app.story.board;
  const removed = new Set(board.removed);
  return Object.keys(board.ranks).filter((h) => !removed.has(h)).sort();
}

function markContext(d) {
  return new MarkContext({
    seats: seatsAt(app.atlas.seats, d.turn),
    seatsBefore: seatsAt(app.atlas.seats, d.turn - 1),
    plans: app.plans,
    plansBefore: app.plansBefore,
    ridingIds: app.ridingIds,
    standing: standing(),
    owners: d.board.owners,
    ownersBefore: d.boardBefore.owners,
    claimSchemes: app.weights.claim_schemes || [],
    cast: app.story.cast(),
    follow: app.follow,
  });
}

function renderTop() {
  const total = app.index.turns;
  const year = el('mv-year');
  const chapter = el('mv-chapter');
  if (calendar()) {
    const y = yearOf(Math.max(1, app.turn));
    year.textContent = app.turn === 0 ? `Before ${y}` : String(y);
    const ch = calendar().chapters.find((c) => c.start_year <= y && y <= c.end_year);
    chapter.textContent = ch ? `Chapter ${ch.numeral} · ${ch.name}` : '';
  } else {
    year.textContent = app.turn === 0 ? 'Before the first' : `${unitName().replace(/^./, (c) => c.toUpperCase())} ${app.turn}`;
    chapter.textContent = `of ${total}`;
  }
  const scrub = el('mv-scrub');
  scrub.max = String(total);
  scrub.value = String(app.turn);
  el('story-next').disabled = app.turn >= total;
}

function renderChips() {
  const box = el('mv-chips');
  const layout = app.layout;
  const parts = [];
  if (!app.d) {
    parts.push(`<p class="mv-banner">Press <b>Next ${escapeHtml(unitName())}</b> to begin, or <b>Auto</b> to let it run.</p>`);
  } else if (layout) {
    for (const c of layout.chips) parts.push(`<span class="mv-chip mv-chip-${c.kind}">${escapeHtml(c.text)}</span>`);
    if (layout.marks.some((m) => m.type === 'crisis')) {
      parts.push('<span class="mv-chip mv-chip-legend"><span class="lg lg-lead">▲ lead</span>'
        + ' <span class="lg lg-resist">▼ resist</span> <span class="lg lg-aside">○ aside</span></span>');
    }
    if (layout.banner) parts.push(`<p class="mv-banner">${escapeHtml(layout.banner)}</p>`);
  }
  box.innerHTML = parts.join('');
}

function renderStandings() {
  const rows = app.d ? app.d.standings : app.story.still();
  el('story-strip').innerHTML = stripHtml(rows, { colourOf, nameOf: titleOf, follow: app.follow });
  const top = rows.slice(0, 3).map((row) => `<span class="swatch" style="background:${escapeHtml(colourOf(row.house) || '#bbb')}"></span>`).join('');
  const lead = rows.length ? escapeHtml(titleOf(rows[0].house)) : 'No house yet';
  el('mv-standings-toggle').innerHTML = `${top}<span class="mv-lead">${lead}</span><span aria-hidden="true">▾</span>`;
}

function renderAfoot() {
  if (app.index.schemes) {
    el('story-plans').hidden = false;
    el('story-plans-list').innerHTML = plansHtml(app.story.plansAfoot() || [], { unit: unitName() });
  }
  const list = app.story.afoot();
  if (app.afoot && !app.story.lines.of(app.afoot)) app.afoot = null;
  const start = calendar() ? calendar().start_year : null;
  el('story-afoot-list').innerHTML = afootHtml(list, { unit: unitName(), selected: app.afoot, start });
  const told = app.afoot ? app.story.tell(app.afoot) : null;
  el('story-afoot-detail').innerHTML = told
    ? storylineHtml(told, { unit: unitName(), link: (turn) => `#${calendar() ? 'turn' : unitName()}-${turn}`, start })
    : '';
  const houses = new Set(told ? told.houses : []);
  const owners = app.story.board.owners;
  for (const [fed, path] of app.paths) path.classList.toggle('afoot', houses.has(owners[fed]));
}

function renderDrawer() {
  const d = app.d;
  el('story-dispatch').innerHTML = d ? dispatchHtml(d, { unit: unitName() }) : '';
  el('story-record-lines').innerHTML = d ? recordHtml(d) : '';
  const more = app.layout ? app.layout.more : 0;
  el('mv-more-count').textContent = more ? ` +${more}` : '';
}

// Chapter closes and the reckoning: a full-screen card over the map.
function renderFull(d) {
  if (!d || (!d.chapter && !d.reckoning)) {
    el('mv-full').hidden = true;
    return;
  }
  const start = calendar() ? calendar().start_year : null;
  el('mv-full-body').innerHTML = (d.chapter ? chapterHtml(d.chapter, { colourOf, nameOf: titleOf, follow: app.follow, start }) : '')
    + (d.reckoning ? reckoningHtml(d.reckoning, { colourOf }) : '');
  el('mv-full').hidden = false;
  el('mv-full').scrollTop = 0;
}

// Show the turn on screen. `jump` (a scrub, a go-to, following again) paints
// without the fill's transition; `frame` asks the camera to frame it.
function show(d, { jump = false, frame = true, full = true } = {}) {
  app.d = d;
  app.layout = d ? marksFor(d, markContext(d), { unit: unitName() }) : null;
  const stage = el('mv-stage');
  if (jump) stage.classList.add('mv-jump');
  paint();
  if (jump) requestAnimationFrame(() => requestAnimationFrame(() => stage.classList.remove('mv-jump')));
  renderTop();
  renderChips();
  renderStandings();
  renderAfoot();
  renderDrawer();
  drawOutlines();
  closeCard();
  if (full) renderFull(d);
  const head = app.layout && app.layout.marks.find((m) => m.headline);
  if (frame) {
    const target = app.camera.frame(frameFor(app.layout));
    if (target) fly(target);
  }
  drawMarks();
  if (head) openCard({ kind: 'mark', id: head.id });
}

async function next() {
  if (app.turn >= app.index.turns) return null;
  const d = await stepTo(app.turn + 1);
  show(d);
  return d;
}

function note(text) {
  const box = el('story-note');
  box.hidden = !text;
  box.textContent = text || '';
}

function stopAuto(reason = '') {
  if (app.auto !== null) clearTimeout(app.auto);
  app.auto = null;
  el('story-auto').textContent = 'Auto';
  el('story-auto').classList.remove('playing');
  note(reason);
}

function startAuto() {
  note('');
  el('mv-full').hidden = true;
  el('story-auto').textContent = 'Pause';
  el('story-auto').classList.add('playing');
  const tick = async () => {
    const d = await guarded(next);
    if (app.auto === null) return;
    if (!d) {
      stopAuto(calendar() ? `The end of the record: ${yearOf(app.index.turns)}.`
        : `The end of the record: ${unitName()} ${app.index.turns}.`);
      return;
    }
    if (d.pause) {
      stopAuto(pauseReason(d));
      return;
    }
    app.auto = setTimeout(tick, SPEEDS[app.speed].ms);
  };
  app.auto = setTimeout(tick, 0);
}

async function guarded(fn) {
  if (app.busy) return null;
  app.busy = true;
  try {
    return await fn();
  } catch (error) {
    stopAuto(`Could not load the record: ${error.message}`);
    return null;
  } finally {
    app.busy = false;
  }
}

// Go to a turn and show it, its chapter close or reckoning included.
async function goTo(target, { full = true } = {}) {
  const turn = Math.max(0, Math.min(app.index.turns, target));
  await guarded(async () => {
    if (turn <= app.turn) reset();
    const d = turn === 0 ? null : await stepTo(turn);
    show(d, { jump: true, full });
  });
}

function hashTurn() {
  const match = /^#(?:season|turn|year)-(\d+)$/.exec(window.location.hash);
  return match ? Number(match[1]) : null;
}

function renderFollow() {
  const select = el('story-follow');
  const byText = (a, b) => (a < b ? -1 : a > b ? 1 : 0);
  const names = Object.keys(app.index.houses).sort((a, b) => byText(titleOf(a), titleOf(b)) || byText(a, b));
  select.innerHTML = '<option value="">no one</option>'
    + names.map((h) => `<option value="${escapeHtml(h)}">${escapeHtml(titleOf(h))}</option>`).join('');
  select.value = app.follow && names.includes(app.follow) ? app.follow : '';
  if (!select.value) app.follow = null;
}

// -------------------------------------------------------------- gestures --

function stagePoint(event) {
  const r = el('mv-stage').getBoundingClientRect();
  return [event.clientX - r.left, event.clientY - r.top];
}

function onTap(x, y) {
  const target = app.downTarget;
  const mark = target && target.closest ? target.closest('[data-mark]') : null;
  if (mark) {
    openCard({ kind: 'mark', id: mark.getAttribute('data-mark') });
    return;
  }
  if (app.card) {
    closeCard();
    return;
  }
  const path = target && target.closest ? target.closest('path[data-fed]') : null;
  if (path && app.story) openCard({ kind: 'riding', fed: path.getAttribute('data-fed') });
}

function handle(events) {
  for (const e of events) {
    if (e.type === 'start') {
      takeCamera();
      app.gesturing = true;
    } else if (e.type === 'pan') {
      applyView(clampView(panBy(app.view, e.dx, e.dy, app.screen), app.world, app.screen, limits()));
    } else if (e.type === 'pinch') {
      let v = panBy(app.view, e.dx, e.dy, app.screen);
      v = zoomAt(v, e.factor, e.x, e.y, app.screen);
      applyView(clampView(v, app.world, app.screen, limits()));
    } else if (e.type === 'end') {
      app.gesturing = false;
      applyView(app.view, { commit: true });
    } else if (e.type === 'tap') {
      onTap(e.x, e.y);
    } else if (e.type === 'doubletap') {
      takeCamera();
      fly(clampView(zoomAt(app.view, 2, e.x, e.y, app.screen), app.world, app.screen, limits()));
    }
  }
}

function wireStage() {
  const stage = el('mv-stage');
  stage.addEventListener('pointerdown', (event) => {
    if (event.button !== undefined && event.button > 0) return;
    if (!app.gestures.pointers.size) app.downTarget = event.target;
    try { stage.setPointerCapture(event.pointerId); } catch (error) { /* a synthetic pointer */ }
    const [x, y] = stagePoint(event);
    handle(app.gestures.down(event.pointerId, x, y, event.timeStamp));
  });
  stage.addEventListener('pointermove', (event) => {
    const [x, y] = stagePoint(event);
    handle(app.gestures.move(event.pointerId, x, y, event.timeStamp));
  });
  const up = (event) => {
    const [x, y] = stagePoint(event);
    handle(app.gestures.up(event.pointerId, x, y, event.timeStamp));
  };
  stage.addEventListener('pointerup', up);
  stage.addEventListener('pointercancel', (event) => handle(app.gestures.cancel(event.pointerId)));
  stage.addEventListener('wheel', (event) => {
    event.preventDefault();
    takeCamera();
    const [x, y] = stagePoint(event);
    const factor = Math.exp(-event.deltaY * (event.deltaMode === 1 ? 0.05 : 0.0018));
    applyView(clampView(zoomAt(app.view, factor, x, y, app.screen), app.world, app.screen, limits()), { commit: true });
  }, { passive: false });
  // Safari's own pinch gesture events would zoom the page; the map takes them.
  for (const name of ['gesturestart', 'gesturechange']) stage.addEventListener(name, (event) => event.preventDefault());
  const card = el('mv-card');
  card.addEventListener('pointerdown', (event) => event.stopPropagation());
  card.addEventListener('click', (event) => {
    if (event.target.closest('.mv-card-close')) closeCard();
  });
}

// The fuller map, fetched the first time the camera comes close.
async function loadDetail() {
  if (app.detail !== 'none') return;
  app.detail = 'loading';
  try {
    const detail = await fetchJson('data/map-detail.json');
    for (const [fed, d] of Object.entries(detail.fills)) {
      const path = app.paths.get(fed);
      if (path) path.setAttribute('d', d);
    }
    el('map-borders').setAttribute('d', detail.borders);
    app.boxes.clear();
    app.points.clear();
    app.detail = 'done';
    drawOutlines();
    drawMarks();
    placeOpenCard();
  } catch (error) {
    app.detail = 'failed';
  }
}

// ----------------------------------------------------------------- setup --

function setOpen(button, panel, open) {
  panel.hidden = !open;
  button.setAttribute('aria-expanded', String(open));
}

function wire() {
  window.addEventListener('hashchange', () => {
    const turn = hashTurn();
    if (turn !== null) { stopAuto(); setOpen(el('mv-drawer-button'), el('mv-drawer'), false); goTo(turn); }
  });
  el('story-next').addEventListener('click', () => { stopAuto(); el('mv-full').hidden = true; guarded(next); });
  el('story-auto').addEventListener('click', () => {
    if (app.auto !== null) stopAuto();
    else startAuto();
  });
  el('mv-speed').addEventListener('click', () => {
    app.speed = (app.speed + 1) % SPEEDS.length;
    el('mv-speed').textContent = SPEEDS[app.speed].label;
    writeStored(SPEED_KEY, String(app.speed));
  });
  el('mv-recentre').addEventListener('click', () => {
    const goal = app.camera.recentre();
    setFree(false);
    if (goal) fly(goal);
  });
  const scrub = el('mv-scrub');
  scrub.addEventListener('input', () => {
    stopAuto();
    const turn = Number(scrub.value);
    el('mv-year').textContent = calendar() ? String(yearOf(Math.max(1, turn))) : `${unitName()} ${turn}`;
  });
  scrub.addEventListener('change', () => goTo(Number(scrub.value), { full: false }));
  el('mv-standings-toggle').addEventListener('click', () => {
    const open = el('mv-standings').hidden;
    setOpen(el('mv-standings-toggle'), el('mv-standings'), open);
  });
  el('mv-drawer-button').addEventListener('click', () => {
    setOpen(el('mv-drawer-button'), el('mv-drawer'), el('mv-drawer').hidden);
  });
  el('mv-drawer-close').addEventListener('click', () => setOpen(el('mv-drawer-button'), el('mv-drawer'), false));
  el('mv-menu-button').addEventListener('click', () => setOpen(el('mv-menu-button'), el('mv-menu'), el('mv-menu').hidden));
  el('mv-menu-close').addEventListener('click', () => setOpen(el('mv-menu-button'), el('mv-menu'), false));
  el('mv-full-continue').addEventListener('click', () => { el('mv-full').hidden = true; });
  el('story-afoot-list').addEventListener('click', (event) => {
    const button = event.target.closest('[data-storyline]');
    if (!button) return;
    const id = button.getAttribute('data-storyline');
    app.afoot = app.afoot === id ? null : id;
    renderAfoot();
  });
  // Following changes the weights and so the headlines, never the game: the
  // story is told again from the start to where the reader stands.
  el('story-follow').addEventListener('change', (event) => {
    app.follow = event.target.value || null;
    writeStored(FOLLOW_KEY, app.follow);
    stopAuto();
    const at = app.turn;
    guarded(async () => {
      reset();
      show(at === 0 ? null : await stepTo(at), { jump: true, full: false });
    });
  });
  document.addEventListener('keydown', (event) => {
    if (event.target.closest && event.target.closest('input, select, textarea')) return;
    if (event.key === 'ArrowRight') { stopAuto(); guarded(next); }
    if (event.key === 'Escape') { closeCard(); el('mv-full').hidden = true; }
  });
  let resizing = null;
  window.addEventListener('resize', () => {
    if (resizing) cancelAnimationFrame(resizing);
    resizing = requestAnimationFrame(() => {
      const centre = app.view ? [app.view.x + app.view.w / 2, app.view.y + app.view.h / 2] : null;
      const w = app.view ? app.view.w : null;
      measure();
      if (centre) applyView(clampView(viewAt(centre[0], centre[1], w, app.screen), app.world, app.screen, limits()), { commit: true });
    });
  });
  wireStage();
}

function prepareMap() {
  const map = el('map');
  map.setAttribute('preserveAspectRatio', 'xMinYMin meet');
  map.removeAttribute('role');
  const borders = el('map-borders');
  borders.setAttribute('vector-effect', 'non-scaling-stroke');
  borders.setAttribute('stroke-width', '0.6');
  for (const path of map.querySelectorAll('#map-fills path')) {
    path.removeAttribute('fill');
    app.paths.set(path.getAttribute('data-fed'), path);
  }
  const full = map.getAttribute('data-view-full').split(/[\s,]+/).map(Number);
  app.world = { x: full[0], y: full[1], w: full[2], h: full[3] };
}

async function boot() {
  try {
    [app.index, app.weights] = await Promise.all([
      fetchJson('data/beats/index.json'),
      fetchJson('story/weights.json'),
    ]);
    app.atlas = await fetchJson('data/beats/atlas.json');
  } catch (error) {
    el('story-load').textContent = `The replay could not be loaded (${error.message}).`;
    return;
  }
  for (const [house, info] of Object.entries(app.index.houses)) {
    app.styles[house] = houseStyle({ house, ...info });
  }
  app.names = readerNames(Object.keys(app.index.houses), (house) => app.styles[house] || null);
  for (const [fed, name] of Object.entries(app.index.ridings || {})) app.ridingIds[name] = fed;
  app.follow = readStored(FOLLOW_KEY);
  const speed = Number(readStored(SPEED_KEY));
  if (Number.isInteger(speed) && speed >= 0 && speed < SPEEDS.length) app.speed = speed;
  el('mv-speed').textContent = SPEEDS[app.speed].label;
  el('story-load').hidden = true;
  el('mv').hidden = false;
  prepareMap();
  measure();
  renderFollow();
  reset();
  wire();
  app.view = homeView();
  app.camera.frame(app.view);
  applyView(app.view, { commit: true });
  show(null, { frame: false });
  // Read-only, for the browser checks (tests/js/mapview.e2e.mjs): where the
  // camera is, its mode, what it framed, and the card open.
  window.hocReplay = {
    turn: () => app.turn,
    busy: () => app.busy || app.flying !== null,
    view: () => ({ ...app.view }),
    mode: () => app.camera.mode,
    frame: () => (app.layout ? [...app.layout.frame] : []),
    marks: () => (app.layout ? app.layout.marks.map((m) => ({ id: m.id, type: m.type, headline: m.headline })) : []),
    card: () => (app.card ? { ...app.card } : null),
  };
  const start = hashTurn();
  if (start !== null) goTo(start);
}

boot();
"""


REPLAY_CSS = r"""/* The Replay as a map (docs/STORY_DESIGN.md §3.6, Phase V). On top of
   style.css; generated by hoc/export/replay_js.py (REPLAY_CSS). Phone upright
   first (390 x 844); an iPad either way round. */
[hidden] { display: none !important; }
html, body.mapview { height: 100%; overflow: hidden; overscroll-behavior: none; }
body.mapview { background: #c9d8e1; }
.mv { position: fixed; inset: 0; height: 100dvh; font-family: var(--sans); }
.mv-load { padding: 1rem; }

/* The stage: the map and what is drawn over it, under the bars. */
.mv-stage { position: absolute; inset: 0; overflow: hidden; touch-action: none; background: #c9d8e1;
  -webkit-user-select: none; user-select: none; -webkit-touch-callout: none; }
.mv-layer { position: absolute; inset: 0; transform-origin: 0 0; will-change: transform; }
.mv-layer #map { width: 100%; height: 100%; display: block; border: 0; background: transparent; overflow: visible; }
#map-fills path { transition: fill 0.9s ease; cursor: default; }
.mv-jump #map-fills path { transition: none; }
#map-fills path.afoot { stroke: var(--ink); stroke-width: 1.6px; vector-effect: non-scaling-stroke; }
.ol { vector-effect: non-scaling-stroke; stroke-linejoin: round; }
.ol-follow { stroke: #111; stroke-width: 2px; }
.ol-mark { stroke: var(--ink); stroke-width: 2.4px; }
.ol-open { stroke: #24617f; stroke-width: 2px; stroke-dasharray: 4 3; }
.ol-claim { stroke: #a3261f; stroke-width: 3px; animation: mv-pulse 1.3s ease-in-out infinite; }
.ol-claim.ol-resolved { animation: none; stroke-width: 2.6px; }
@keyframes mv-pulse { 0%, 100% { stroke-opacity: 1; } 50% { stroke-opacity: 0.25; } }

/* Marks: drawn in screen pixels, so their size never changes with the zoom. */
.mv-marks { position: absolute; inset: 0; width: 100%; height: 100%; pointer-events: none; overflow: visible; }
.mk { pointer-events: auto; cursor: pointer; }
.mk-hit { fill: transparent; }
.mk-bg { fill: #fff; stroke: var(--ink); stroke-width: 1.5; }
.mk-head .mk-bg { stroke: var(--accent); stroke-width: 3; }
.mk-small .mk-bg { stroke-width: 1.2; }
.g-fill { fill: var(--ink); }
.g-line { fill: none; stroke: var(--ink); stroke-width: 1.8; stroke-linecap: round; stroke-linejoin: round; }
.g-bold { stroke-width: 2.8; }
.mk-claim .g-fill { fill: #a3261f; } .mk-claim .g-line { stroke: #a3261f; }
.mk-strife .g-fill { fill: #b03030; }
.mk-bond .g-line { stroke: #8a6a10; }
.mk-lead .g-fill { fill: #2f6b2a; }
.mk-resist .g-fill { fill: #5b3f8f; }
.mk-aside .g-line { stroke: #8a8478; }
.mk-label { font: 600 11px var(--sans); text-anchor: middle; fill: var(--ink); paint-order: stroke;
  stroke: #fff; stroke-width: 3.5px; stroke-linejoin: round; }
.mk-label-head { font-size: 12px; }
.mk-label { pointer-events: none; }
.ln-leader { stroke: var(--ink); stroke-width: 1.2; stroke-opacity: 0.6; }
.ln-pin { fill: var(--ink); }
.ln { fill: none; stroke-linecap: round; }
.ln-casing { stroke: rgba(255,255,255,0.85); stroke-width: 6; }
.ln-bond { stroke: #b8860b; stroke-width: 3.2; }
.ln-strife { stroke: #b03030; stroke-width: 2.6; stroke-dasharray: 7 5; }
.ln-claim { stroke: #a3261f; stroke-width: 2.4; stroke-dasharray: 8 4; }
.ln-scheme { stroke: var(--ink); stroke-width: 2; }
.ln-intent { stroke: var(--ink); stroke-opacity: 0.5; stroke-width: 1.5; stroke-dasharray: 2 4; }
.ln-origin { fill: #fff; stroke: var(--ink); stroke-width: 1.5; }
.mv-arrowhead { fill: var(--ink); }
.mv-arrowhead-faint { fill: rgba(31,28,23,0.5); }

/* The bars over the map. */
.mv-top { position: absolute; top: 0; left: 0; right: 0; z-index: 10; border: 0;
  padding: calc(6px + env(safe-area-inset-top)) 10px 6px;
  background: linear-gradient(rgba(251,250,247,0.97), rgba(251,250,247,0.9));
  box-shadow: 0 1px 6px rgba(0,0,0,0.12); }
.mv-topline { display: flex; align-items: center; gap: 8px; }
.mv-icon { font-size: 1.15rem; line-height: 1; width: 40px; height: 40px; border-radius: 50%;
  border: 1px solid var(--rule); background: #fff; color: var(--ink); flex: none; }
.mv-when { display: flex; flex-direction: column; min-width: 0; flex: 1; line-height: 1.1; }
.mv-year { font-family: var(--serif); font-size: 1.45rem; font-weight: 600; }
.mv-chapter { font-size: 0.74rem; color: var(--muted); white-space: nowrap; overflow: hidden; text-overflow: ellipsis; }
.mv-standings-toggle { margin-left: auto; display: flex; align-items: center; gap: 3px; max-width: 40%; flex: none;
  font: inherit; font-size: 0.8rem; padding: 0.35rem 0.6rem; border-radius: 999px; border: 1px solid var(--rule);
  background: #fff; color: var(--ink); min-height: 40px; }
.mv-standings-toggle .swatch { margin: 0; }
.mv-lead { margin-left: 4px; white-space: nowrap; overflow: hidden; text-overflow: ellipsis; }
.mv-scrub { width: 100%; height: 22px; margin: 4px 0 0; accent-color: var(--accent); display: block; }
.mv-tag { margin: 0; font-size: 0.7rem; color: var(--muted); }
.mv-chips { display: flex; flex-wrap: wrap; gap: 5px; margin-top: 3px; }
.mv-chips:empty { display: none; }
.mv-chip { font-size: 0.74rem; padding: 0.12rem 0.55rem; border-radius: 999px; background: #fff;
  border: 1px solid var(--rule); color: var(--ink); }
.mv-chip-quiet { font-style: italic; color: var(--muted); }
.mv-chip-event { border-color: #a0762a; }
.lg-lead { color: #2f6b2a; } .lg-resist { color: #5b3f8f; } .lg-aside { color: #8a8478; }
.mv-banner { margin: 2px 0 0; font-family: var(--serif); font-size: 0.92rem; background: #fff;
  border-radius: 8px; padding: 0.4rem 0.6rem; border: 1px solid var(--rule); width: 100%; }
.mv-standings { margin-top: 6px; max-height: 52dvh; overflow: auto; border-top: 1px solid var(--rule); padding-top: 4px; }
.mv-standings-list { list-style: none; margin: 0; padding: 0; }
.mv-standings-list .standing { padding: 0.32rem 0; border-bottom: 1px solid var(--rule); font-size: 0.92rem; }
.mv-follow { display: block; margin: 0.5rem 0 0.2rem; font-size: 0.85rem; }
.mv-follow select { font: inherit; max-width: 70%; }

.mv-bottom { position: absolute; left: 0; right: 0; bottom: 0; z-index: 10; border: 0; margin: 0;
  padding: 8px 10px calc(8px + env(safe-area-inset-bottom));
  background: linear-gradient(rgba(251,250,247,0.88), rgba(251,250,247,0.97)); box-shadow: 0 -1px 6px rgba(0,0,0,0.1); }
.mv-controls { display: flex; gap: 8px; justify-content: center; align-items: center; }
.mv button { font: inherit; }
.mv-controls button, .mv-drawer-head button, .mv-menu button, .mv-full button {
  font-size: 0.92rem; min-height: 44px; padding: 0.4rem 0.85rem; border-radius: 999px;
  border: 1px solid var(--rule); background: #fff; color: var(--ink); }
.mv-controls button.primary, .mv-full button.primary { background: var(--accent); border-color: var(--accent);
  color: #fff; font-weight: 600; }
.mv-controls button.playing { border-color: var(--accent); color: var(--accent); font-weight: 600; }
.mv-controls button:disabled { opacity: 0.45; }
.mv-speed { min-width: 44px; padding: 0.4rem 0.5rem !important; }
.mv-recentre { position: absolute; right: 12px; bottom: calc(100% + 10px); box-shadow: 0 1px 5px rgba(0,0,0,0.25); }
.mv-more-count { font-weight: 600; color: var(--accent); }
.mv-note { margin: 0 0 6px; font-size: 0.78rem; text-align: center; color: var(--ink); }

/* One card at a time, attached to its mark. */
.mv-card { position: absolute; top: 0; left: 0; z-index: 5; width: min(340px, calc(100vw - 16px));
  max-height: 42dvh; overflow: auto; background: #fff; border-radius: 10px; padding: 10px 34px 10px 12px;
  box-shadow: 0 3px 14px rgba(0,0,0,0.22); border: 1px solid rgba(0,0,0,0.08); font-size: 0.9rem; }
.mv-card-close { position: absolute; top: 4px; right: 4px; width: 32px; height: 32px; border: 0; background: none;
  font-size: 1.3rem; line-height: 1; color: var(--muted); }
.mv-card-kicker { margin: 0 0 0.2rem; font-size: 0.72rem; text-transform: uppercase; letter-spacing: 0.04em; color: var(--accent); }
.mv-card-title { margin: 0 0 0.2rem; border: 0; padding: 0; font-size: 1.05rem; }
.mv-card-text { margin: 0.1rem 0; font-family: var(--serif); line-height: 1.38; }
.mv-card-headline { font-size: 1.04rem; }
.mv-card-previously { margin: 0.35rem 0 0; font-size: 0.8rem; color: var(--muted); font-family: var(--serif); }
.mv-card-legend { margin: 0.3rem 0 0; font-size: 0.8rem; }

/* The drawer: the dispatch, Plans afoot, Afoot and the full record. */
.mv-drawer { position: absolute; left: 0; right: 0; bottom: 0; z-index: 30; max-height: 74dvh; overflow: auto;
  background: var(--paper); border-radius: 14px 14px 0 0; box-shadow: 0 -4px 18px rgba(0,0,0,0.25);
  padding: 0 14px calc(18px + env(safe-area-inset-bottom)); }
.mv-drawer-head { position: sticky; top: 0; display: flex; align-items: center; justify-content: space-between;
  background: var(--paper); padding: 8px 0; border-bottom: 1px solid var(--rule); z-index: 1; }
.mv-drawer-title { font-family: var(--serif); font-weight: 600; }
.mv-drawer .afoot-heading, .mv-drawer h2 { margin-top: 1rem; }
.mv-menu { position: absolute; top: 0; left: 0; bottom: 0; z-index: 40; display: block; margin: 0;
  width: min(320px, 86vw); overflow: auto; background: var(--paper); box-shadow: 4px 0 18px rgba(0,0,0,0.25);
  padding: calc(14px + env(safe-area-inset-top)) 16px 20px; }
.mv-game { font-family: var(--serif); color: var(--muted); margin: 0.2rem 0 0.6rem; }
.mv-links a { display: block; padding: 0.45rem 0; font-size: 0.95rem; border-bottom: 1px solid var(--rule); }
.mv-full { position: absolute; inset: 0; z-index: 50; overflow: auto; background: rgba(251,250,247,0.98);
  padding: calc(16px + env(safe-area-inset-top)) 16px calc(24px + env(safe-area-inset-bottom)); }
.mv-full-body { max-width: 40rem; margin: 0 auto; }
.mv-full > button { display: block; margin: 1rem auto 0; min-width: 9rem; }

@media (min-width: 760px) {
  .mv-drawer { left: auto; top: 0; width: 420px; max-height: none; border-radius: 0;
    box-shadow: -4px 0 18px rgba(0,0,0,0.25); }
  .mv-top, .mv-bottom { padding-left: 16px; padding-right: 16px; }
  .mv-card { width: 360px; }
  .mv-standings { max-width: 26rem; margin-left: auto; }
}
@media (prefers-reduced-motion: reduce) {
  #map-fills path { transition: none; }
  .ol-claim { animation: none; }
}
"""


REPLAY_TEXT_JS = r"""// A frozen game, told one turn at a time, in a column of text.
//
// Generated by hoc/export/replay_js.py (REPLAY_TEXT_JS). The story layer is ./story/ (web/story/
// on export); the beats are ./data/beats/, typed from the game's record by
// hoc/export/beats.py and fetched a chunk at a time as they are needed.

import { Story } from './story/dispatch.js';
import { houseStyle, readerNames } from './story/text.js';
import {
  MapCamera, afootHtml, chapterHtml, dispatchHtml, escapeHtml, pauseReason, plansHtml, readStored,
  reckoningHtml, recordHtml, storylineHtml, stripHtml, writeStored,
} from './story/view.js';

const SCENARIO = __SCENARIO__;
const FOLLOW_KEY = `hoc-story-follow:${SCENARIO}`;
const UNCLAIMED_FILL = '__UNCLAIMED_FILL__';
const AUTO_MS = 1600;

const el = (id) => document.getElementById(id);

const app = {
  index: null,
  weights: null,
  chunks: new Map(),
  story: null,
  turn: 0,
  follow: null,
  auto: null,
  busy: false,
  camera: null,
  paths: [],
  styles: {},
  // What a reader calls each house: its surname, or its title where two
  // houses of the game share one (story/text.js readerNames). Never a numeral.
  names: new Map(),
  // The storyline open in the Afoot panel, if any.
  afoot: null,
};

async function fetchJson(url) {
  const response = await fetch(url);
  if (!response.ok) throw new Error(`${url}: HTTP ${response.status}`);
  return response.json();
}

// The chunk holding `turn`, fetched the first time it is needed: the turn's
// beats, and its prestige where the record carries it (rules 1.0).
async function turnData(turn) {
  const entry = app.index.chunks.find((c) => c.first <= turn && turn <= c.last);
  if (!entry) return { beats: [], prestige: null, plans: null };
  if (!app.chunks.has(entry.file)) {
    app.chunks.set(entry.file, fetchJson(`data/beats/${entry.file}`));
  }
  const chunk = await app.chunks.get(entry.file);
  return {
    beats: chunk.turns[String(turn)] || [],
    prestige: (chunk.prestige && chunk.prestige[String(turn)]) || null,
    // Rules 1.0 `schemes`: every public scheme as the turn left them.
    plans: chunk.plans ? (chunk.plans[String(turn)] || []) : null,
  };
}

function nameOf(house) {
  return app.names.get(house) || house.replace(/ \d+$/, '');
}

function colourOf(house) {
  const info = app.index.houses[house];
  return info && info.colour ? info.colour : null;
}

// Rules 1.0 `world_calendar`: a turn is a year, told by its year.
function calendar() {
  return app.index.calendar || null;
}

function unitName() {
  if (calendar()) return 'year';
  return app.index.unit === 'turn' ? 'turn' : 'season';
}

function startYear() {
  return calendar() ? calendar().start_year : null;
}

// How a turn is linked: #season-N, #turn-N, and #turn-N for a calendar game.
function anchor(turn) {
  return `#${calendar() ? 'turn' : unitName()}-${turn}`;
}

function reset() {
  app.story = new Story({
    weights: app.weights,
    baseline: app.index.baseline,
    follow: app.follow,
    unit: unitName(),
    styleOf: (house) => app.styles[house] || null,
    ridings: app.index.ridings || {},
    watch: Boolean(app.index.succession_watch),
    calendar: calendar(),
    reckoning: app.index.reckoning || null,
  });
  app.turn = 0;
}

async function stepTo(target) {
  let last = null;
  while (app.turn < target) {
    const { beats, prestige, plans } = await turnData(app.turn + 1);
    last = app.story.step(app.turn + 1, beats, { prestige, plans });
    app.turn += 1;
  }
  return last;
}

function paint() {
  const owners = app.story.board.owners;
  for (const path of app.paths) {
    const house = owners[path.getAttribute('data-fed')];
    path.setAttribute('fill', (house && colourOf(house)) || UNCLAIMED_FILL);
  }
}

// Where to point the camera: the headline's ridings, or, for a beat that moved
// none (a quarrel, a marriage), every riding its houses hold.
function focusOf(d) {
  if (!d || d.quiet) return [];
  if (d.zoom.length) return d.zoom;
  const houses = new Set(d.headline.beat.houses || []);
  return Object.entries(app.story.board.owners)
    .filter(([, house]) => houses.has(house))
    .map(([fed]) => fed);
}

function renderLabel() {
  const total = app.index.turns;
  if (calendar()) {
    el('story-turn').textContent = app.turn === 0
      ? `before ${startYear()} (turn 1 of ${total})`
      : `${startYear() + app.turn - 1} (turn ${app.turn} of ${total})`;
  } else {
    el('story-turn').textContent = app.turn === 0
      ? `before ${unitName()} 1 of ${total}`
      : `${unitName()} ${app.turn} of ${total}`;
  }
  el('story-next').disabled = app.turn >= total;
}

// The Afoot panel: open storylines; the chosen one's beats, and its houses
// marked on the map.
function renderAfoot() {
  // Plans afoot, above Afoot, for a record that carries schemes (rules 1.0).
  if (app.index.schemes) {
    el('story-plans').hidden = false;
    el('story-plans-list').innerHTML = plansHtml(app.story.plansAfoot() || [], { unit: unitName() });
  }
  const list = app.story.afoot();
  if (app.afoot && !app.story.lines.of(app.afoot)) app.afoot = null;
  el('story-afoot-list').innerHTML = afootHtml(list, { unit: unitName(), selected: app.afoot, start: startYear() });
  const told = app.afoot ? app.story.tell(app.afoot) : null;
  el('story-afoot-detail').innerHTML = told
    ? storylineHtml(told, { unit: unitName(), link: anchor, start: startYear() })
    : '';
  const houses = new Set(told ? told.houses : []);
  const owners = app.story.board.owners;
  for (const path of app.paths) {
    path.classList.toggle('afoot', houses.has(owners[path.getAttribute('data-fed')]));
  }
}

function show(d, { zoom = true } = {}) {
  paint();
  renderLabel();
  renderAfoot();
  el('story-strip').innerHTML = stripHtml(d ? d.standings : app.story.still(), { colourOf, nameOf, follow: app.follow });
  if (!d) {
    el('story-dispatch').innerHTML =
      `<p class="dispatch-quiet">Press <b>Next ${unitName()}</b> to begin, or <b>Auto</b> to let it run.</p>`;
    el('story-record-lines').innerHTML = '';
    return;
  }
  // Phase D1: a chapter's interstitial at its end, and the reckoning after the last turn.
  el('story-dispatch').innerHTML = dispatchHtml(d, { unit: unitName() })
    + (d.chapter ? chapterHtml(d.chapter, { colourOf, nameOf, follow: app.follow, start: startYear() }) : '')
    + (d.reckoning ? reckoningHtml(d.reckoning, { colourOf }) : '');
  el('story-record-lines').innerHTML = recordHtml(d);
  if (zoom && app.camera) app.camera.focus(focusOf(d));
}

async function next() {
  if (app.turn >= app.index.turns) return null;
  const d = await stepTo(app.turn + 1);
  show(d);
  return d;
}

function note(text) {
  const box = el('story-note');
  box.hidden = !text;
  box.textContent = text || '';
}

function stopAuto(reason = '') {
  if (app.auto !== null) clearTimeout(app.auto);
  app.auto = null;
  el('story-auto').textContent = 'Auto';
  el('story-auto').classList.remove('playing');
  note(reason);
}

function startAuto() {
  note('');
  el('story-auto').textContent = 'Pause';
  el('story-auto').classList.add('playing');
  const tick = async () => {
    const d = await guarded(next);
    if (app.auto === null) return;
    if (!d) {
      stopAuto(calendar() ? `The end of the record: ${startYear() + app.index.turns - 1}.`
        : `The end of the record: ${unitName()} ${app.index.turns}.`);
      return;
    }
    if (d.pause) {
      stopAuto(pauseReason(d));
      return;
    }
    app.auto = setTimeout(tick, AUTO_MS);
  };
  app.auto = setTimeout(tick, 0);
}

// One thing at a time: a press while a chunk is loading is ignored rather than
// queued, so Next never skips a turn.
async function guarded(fn) {
  if (app.busy) return null;
  app.busy = true;
  try {
    return await fn();
  } catch (error) {
    stopAuto(`Could not load the record: ${error.message}`);
    return null;
  } finally {
    app.busy = false;
  }
}

// Go to a turn and show its dispatch (with its interstitial or reckoning).
// Telling it again from the start when it is not ahead means the turn already
// on screen, asked for again, is shown and not the opening prompt.
async function goTo(target) {
  const turn = Math.max(0, Math.min(app.index.turns, target));
  await guarded(async () => {
    if (turn <= app.turn) reset();
    const d = turn === 0 ? null : await stepTo(turn);
    show(d, { zoom: false });
  });
}

// The go-to box: a year in a calendar game (1885), or a turn.
function wantedTurn(value) {
  if (calendar() && value >= startYear()) return value - startYear() + 1;
  return value;
}

function renderFollow() {
  const select = el('story-follow');
  const byText = (a, b) => (a < b ? -1 : a > b ? 1 : 0);
  const names = Object.keys(app.index.houses).sort((a, b) => byText(nameOf(a), nameOf(b)) || byText(a, b));
  select.innerHTML = '<option value="">no one</option>'
    + names.map((h) => `<option value="${escapeHtml(h)}">${escapeHtml(nameOf(h))}</option>`).join('');
  select.value = app.follow && names.includes(app.follow) ? app.follow : '';
  if (!select.value) app.follow = null;
}

// replay.html#season-88 (or #turn-2) opens the replay at that turn: the
// Storylines page links each beat here.
function hashTurn() {
  const match = /^#(?:season|turn|year)-(\d+)$/.exec(window.location.hash);
  return match ? Number(match[1]) : null;
}

function wire() {
  window.addEventListener('hashchange', () => {
    const turn = hashTurn();
    if (turn !== null) { stopAuto(); goTo(turn); }
  });
  el('story-afoot-list').addEventListener('click', (event) => {
    const button = event.target.closest('[data-storyline]');
    if (!button) return;
    const id = button.getAttribute('data-storyline');
    app.afoot = app.afoot === id ? null : id;
    renderAfoot();
  });
  el('story-next').addEventListener('click', () => { stopAuto(); guarded(next); });
  el('story-auto').addEventListener('click', () => {
    if (app.auto !== null) stopAuto();
    else startAuto();
  });
  el('story-start').addEventListener('click', () => { stopAuto(); goTo(0); });
  el('story-goto').addEventListener('submit', (event) => {
    event.preventDefault();
    stopAuto();
    goTo(wantedTurn(Number(el('story-goto-turn').value) || 0));
  });
  // Following changes the weights and so the headlines, never the game: the
  // story is told again from the start to where the reader stands.
  el('story-follow').addEventListener('change', (event) => {
    app.follow = event.target.value || null;
    writeStored(FOLLOW_KEY, app.follow);
    stopAuto();
    const at = app.turn;
    guarded(async () => {
      reset();
      show(at === 0 ? null : await stepTo(at), { zoom: false });
    });
  });
  const map = el('map');
  const toggle = el('view-toggle');
  toggle.addEventListener('click', () => {
    if (app.camera) app.camera.reset();
    const south = toggle.getAttribute('data-showing') !== 'full';
    map.setAttribute('viewBox', map.getAttribute(south ? 'data-view-full' : 'data-view-south'));
    el('map-borders').setAttribute(
      'stroke-width', map.getAttribute(south ? 'data-stroke-full' : 'data-stroke-south'),
    );
    toggle.setAttribute('data-showing', south ? 'full' : 'south');
    toggle.textContent = south ? 'Show the south' : 'Show the north';
  });
}

async function boot() {
  try {
    [app.index, app.weights] = await Promise.all([
      fetchJson('data/beats/index.json'),
      fetchJson('story/weights.json'),
    ]);
  } catch (error) {
    el('story-load').textContent = `The replay could not be loaded (${error.message}).`;
    return;
  }
  app.paths = [...document.querySelectorAll('#map-fills path')];
  for (const [house, info] of Object.entries(app.index.houses)) {
    app.styles[house] = houseStyle({ house, ...info });
  }
  app.names = readerNames(Object.keys(app.index.houses), (house) => app.styles[house] || null);
  app.camera = new MapCamera(el('map'), { borders: el('map-borders') });
  app.follow = readStored(FOLLOW_KEY);
  if (!calendar()) el('story-goto-turn').max = String(app.index.turns);
  renderFollow();
  reset();
  wire();
  show(null);
  el('story-load').hidden = true;
  el('story-app').hidden = false;
  const start = hashTurn();
  if (start !== null) goTo(start);
}

boot();
"""


STORYLINES_JS = r"""// Every storyline of a frozen game, told top to bottom.
//
// Generated by hoc/export/replay_js.py. Built here, in the browser, from the
// same beat data the Replay reads, by the same story layer (./story/): the
// game is replayed as dispatches and its storylines listed by type. Nothing
// about storylines is computed in Python.

import { Story } from './story/dispatch.js';
import { STORYLINE_TYPES } from './story/storylines.js';
import { houseStyle } from './story/text.js';
import { escapeHtml, storylineHtml } from './story/view.js';

const HEADINGS = {
  rivalry: 'Rivalries', union: 'Unions', succession: 'Succession questions',
  rise: 'Rises', decline: 'Declines', frontier: 'Frontiers',
};

const el = (id) => document.getElementById(id);

async function fetchJson(url) {
  const response = await fetch(url);
  if (!response.ok) throw new Error(`${url}: HTTP ${response.status}`);
  return response.json();
}

async function boot() {
  let index;
  let weights;
  let chunks;
  try {
    [index, weights] = await Promise.all([
      fetchJson('data/beats/index.json'),
      fetchJson('story/weights.json'),
    ]);
    chunks = await Promise.all(index.chunks.map((c) => fetchJson(`data/beats/${c.file}`)));
  } catch (error) {
    el('lines-load').textContent = `The storylines could not be loaded (${error.message}).`;
    return;
  }
  const byTurn = {};
  const prestige = {};
  for (const chunk of chunks) {
    Object.assign(byTurn, chunk.turns);
    Object.assign(prestige, chunk.prestige || {});
  }
  const styles = {};
  for (const [house, info] of Object.entries(index.houses)) styles[house] = houseStyle({ house, ...info });
  // Rules 1.0 `world_calendar`: a turn is a year, told by its year.
  const calendar = index.calendar || null;
  const start = calendar ? calendar.start_year : null;
  const unit = calendar ? 'year' : (index.unit === 'turn' ? 'turn' : 'season');
  const anchor = calendar ? 'turn' : unit;
  const span = (s) => (calendar
    ? (s.state === 'closed' ? `${start + s.opened - 1}–${start + s.closed - 1}` : `since ${start + s.opened - 1}`)
    : (s.state === 'closed' ? `${unit}s ${s.opened}–${s.closed}` : `since ${unit} ${s.opened}`));
  const story = new Story({
    weights, baseline: index.baseline, unit,
    styleOf: (house) => styles[house] || null, ridings: index.ridings || {},
    watch: Boolean(index.succession_watch), calendar, reckoning: index.reckoning || null,
  });
  for (let turn = 1; turn <= index.turns; turn += 1) {
    story.step(turn, byTurn[String(turn)] || [], { prestige: prestige[String(turn)] || null });
  }

  const all = story.lines.all;
  const sections = [];
  const contents = [];
  for (const type of STORYLINE_TYPES) {
    const lines = all.filter((s) => s.type === type).sort((a, b) => a.opened - b.opened || (a.id < b.id ? -1 : 1));
    if (!lines.length) continue;
    contents.push(`<a href="#type-${type}">${HEADINGS[type]} (${lines.length})</a>`);
    const items = lines.map((s) => {
      const told = story.tell(s.id);
      const end = span(s);
      return `<details class="storyline" id="${escapeHtml(s.id)}"><summary>`
        + `<span class="storyline-title">${escapeHtml(told.name)}</span>`
        + `<span class="meta"> ${told.beats.length} beat${told.beats.length === 1 ? '' : 's'} &middot; ${end}`
        + ` &middot; ${escapeHtml(s.state === 'closed' ? s.outcome : s.state)}</span></summary>`
        + storylineHtml(told, { unit, link: (turn) => `replay.html#${anchor}-${turn}`, start })
        + '</details>';
    });
    sections.push(`<section id="type-${type}" class="storyline-type"><h2>${HEADINGS[type]}`
      + ` <span class="count">${lines.length}</span></h2>${items.join('')}</section>`);
  }
  const closed = all.filter((s) => s.state === 'closed').length;
  el('lines-summary').textContent = `${all.length} storylines over ${calendar
    ? `the years ${start}–${start + index.turns - 1}` : `${index.turns} ${unit}s`}:`
    + ` ${closed} closed, ${all.length - closed} still open when the record ends.`;
  el('lines-types').innerHTML = contents.join(' &middot; ');
  el('lines-body').innerHTML = sections.join('') || '<p class="meta">This game has no storylines.</p>';
  el('lines-load').hidden = true;
  el('lines-app').hidden = false;
  if (window.location.hash) {
    const target = document.getElementById(window.location.hash.slice(1));
    if (target && target.tagName === 'DETAILS') target.open = true;
    if (target) target.scrollIntoView();
  }
}

boot();
"""


RECKONING_JS = r"""// The reckoning after a calendar game's last turn (Phase D1).
//
// Generated by hoc/export/replay_js.py. The final table and an epilogue for
// every house ever of the top eight, built in the browser by the story layer
// (./story/reckoning.js) from the reckoning record the engine wrote, which
// hoc/export/beats.py ships in the beat index. Nothing here adds a fact.

import { reckoningView } from './story/reckoning.js';
import { houseStyle } from './story/text.js';
import { reckoningHtml } from './story/view.js';

const el = (id) => document.getElementById(id);

async function boot() {
  let index;
  try {
    const response = await fetch('data/beats/index.json');
    if (!response.ok) throw new Error(`HTTP ${response.status}`);
    index = await response.json();
  } catch (error) {
    el('reckoning-load').textContent = `The reckoning could not be loaded (${error.message}).`;
    return;
  }
  if (!index.reckoning) {
    el('reckoning-load').textContent = 'This game has no reckoning: it was not played to the end of a calendar.';
    return;
  }
  const styles = {};
  for (const [house, info] of Object.entries(index.houses)) styles[house] = houseStyle({ house, ...info });
  const view = reckoningView(index.reckoning, { styleOf: (house) => styles[house] || null });
  const colourOf = (house) => (index.houses[house] && index.houses[house].colour) || null;
  el('reckoning-body').innerHTML = reckoningHtml(view, { colourOf });
  el('reckoning-load').hidden = true;
}

boot();
"""
